### ISSUE TITLE
matlab kernel not showing

### ISSUE THREAD

**Issue by TheMadHatter666** [Calysto/matlab_kernel#100]
I was having some issues running  (the kernel kept crashing) so I tried reinstalling Anaconda and then the kernel.  But Jupyter seemed to recall the old installation so I used the command
jupyter kernelspec remove matlab

That removed the kernel.  
But then, when I subsequently run  pip install matlab_kernel
it says requirements already met.  But it does not work.  
Matlab kernel does not show in the dropdown and jupyter kernelspec list  does not show matlab.

At a loss.

**Comment by anntzer** [comment]
Try `python -m matlab_kernel install`?

**Comment by TheMadHatter666** [comment]
Thanks.  That worked.  Now I am back where I started.  Kernel works but keeps randomly crashing.

**Comment by dsblank** [comment]
Did you fix your issue?
