### ISSUE TITLE
Logo problem

### ISSUE THREAD

**Issue by JuanRdBO** [Calysto/matlab_kernel#102]
When executing `python -m matlab_kernel install` it does not find the kernel logo and throws the following exception:

`IOError: [Errno 2] No such file or directory: '/Users/$username/anaconda2/lib/python2.7/site-packages/matlab_kernel/images/logo-64x64.png'`

To fix this issue i copied the images folder in the metakernel folder `/Users/$username/anaconda2/lib/python2.7/site-packages/metakernel` and just pasted it in the MatLab kernel folder `/Users/$username/anaconda2/lib/python2.7/site-packages/matlab_kernel`. And it worked.

**Comment by blink1073** [comment]
What does `conda list metakernel` show?  Also, was the output a direct result of `python -m matlab_kernel install` or from running something else afterward?

**Comment by MRIO** [comment]
In my case it was the result of `python -m matlab_kernel install`.

**Comment by JuanRdBO** [comment]
It was the result of running `python -m matlab_kernel install`
