### ISSUE TITLE
Cell execution timeout when using nbconvert with wurlitzer

### ISSUE THREAD

**Issue by auneri** [Calysto/matlab_kernel#104]
The default behavior to use the distributed wurlitzer [when available](https://github.com/Calysto/matlab_kernel/blob/v0.15.0/matlab_kernel/kernel.py#L24-L27) (i.e., on UNIX) causes intermittent cell execution timeouts when using nbconvert.

While I can copy paste the error log, deleting the module file --or better yet-- replacing it with the upstream one at https://github.com/minrk/wurlitzer seems to fix it. I believe the correct approach here (that also properly acknowledges the original author) would be to have wurlitzer as an external dependency. Unless of course there are custom changes in the distributed version?

**Comment by dsblank** [comment]
Thanks for the fix, and suggestion. @blink1073 any reason we can't now depend on it as a dependency?

**Comment by dsblank** [comment]
Any chance you could make a PR?

**Comment by jayendra13** [comment]
ok let me do that

**Comment by jayendra13** [comment]
Here you go https://github.com/Calysto/matlab_kernel/pull/118
