### ISSUE TITLE
Ubuntu 16.06 and git master: error

### ISSUE THREAD

**Issue by ouboub** [Calysto/matlab_kernel#108]
Hi

I am using Ubuntu 16.06 and upgraded my pip version to 10. 
when running pip install matlab_kernel
I obtain 
```

File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```

What shall I do?

Uwe Brauer

**Comment by ouboub** [comment]
this is a bug in pip 10, I downgraded to pip 9.03 and that solved this issue, but there is another one, which I have to report separately. This issue you can close, please.

**Comment by blink1073** [comment]
Closing...
