### ISSUE TITLE
MATLAB does not terminate when started via nbconvert --execute

### ISSUE THREAD

**Issue by auneri** [Calysto/matlab_kernel#11]
Unlike the standard workflow whereby closing a notebook does terminate MATLAB, using `ipython nbconvert --execute`, it has to be terminated manually. The relevant use case is when generating the notebooks nightly for documentation and testing purposes. Only tested on Windows so far..

Thank you for this great work, and let me know if I can help (with some pointers on where to look).

**Comment by blink1073** [comment]
Hi @auneri, it looks like IPython is not properly shutting down the kernel, or allowing any `atexit` calls to fire.  I added an `atexit` call to write to a file, and added the same code in the `do_shutdown` method provided for IPython zmq kernels, and neither one was fired.

**Comment by auneri** [comment]
Using jupyter notebook (tested on v4.0.6), it seems like these signals are now connected properly.

Due to changes introduced in commit de0f7c65f50007905d052d47495feb8cf63ba4e6 I now see a MATLAB desktop environment launched at startup, and a `test.txt` created on exit.

**Comment by blink1073** [comment]
Great, so we can close this?

**Comment by auneri** [comment]
Well, actually not quite yet. The initial problem still remains, after calling `jupyter nbconvert --execute`, MATLAB process does not terminate. It seems whatever has been fixed for notebook was not applied to nbconvert project.

**Comment by blink1073** [comment]
Bummer.

**Comment by auneri** [comment]
Could we merge #23 in the meantime, don't think they should be on the master branch anyway.

**Comment by anntzer** [comment]
Seems fixed now.  Feel free to request a reopen if applicable.

**Comment by auneri** [comment]
Confirmed that it works, thanks!
