### ISSUE TITLE
Error with Libraries

### ISSUE THREAD

**Issue by bashterm** [Calysto/matlab_kernel#110]
I'm getting an error with the libstdc++.so.6 library included with matlab. Jupyter Enterprise Kernel Gateway is complaining:
```
Aug 10 19:38:48 5460b7e517d4 start.sh[68]: ImportError: /opt/lic/MATLAB/R2017b/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/bin/jupyterkg/workdir/.conda/envs/jupyterkgenv/lib/python3.5/site-packages/zmq/backend/cython/../../../../../libzmq.so.5)
```

I've exported by LD_LIBRARY_PATH like such:
```
export LD_LIBRARY_PATH="/usr/lib64/:$matlabroot/bin/glnax64:$matlabroot/sys/os/glnax64:$LD_LIBRARY_PATH"
```

I'm not sure what's up. Has anyone  encoutnered this problem before, and if so, how have you fixed it?

**Comment by dsblank** [comment]
You might have to pass that environment variable on to Jupyter or JupyterHub. I think that there is an option in the JSON kernel to list the environment variables to pass, but not sure...

**Comment by bashterm** [comment]
There is. Do you know how I pass special values at install time? 

In other words, when i run `python -mmatlab_kernel install`, how do I pass that environment variable in so that it gets initialized with the kernelspecs?

**Comment by dsblank** [comment]
If you can, it would be easiest to just create the kernel.json file and then edit it.

**Comment by bashterm** [comment]
I'll give that a try.

Thanks!

**Comment by dsblank** [comment]
Ok, good luck! Let us know if that fixes it.

**Comment by david11rsww** [comment]
I also faced the same problem, in docker ubuntu.
