### ISSUE TITLE
libstdc++.so.6: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by david11rsww** [Calysto/matlab_kernel#112]
when I start the matlab kernel, something is wrong!
```
ImportError: /usr/local/matlab/2017b/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../sys/os/glnxa64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/anoconda/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../../libzmq.so.5)
```
When in local env, it is OK. When use  jupyter kernel, it is wrong.
Can anyone give me a detail way to solve it?

**Comment by david11rsww** [comment]
This problem have been soleved.

**Comment by tsungruihon** [comment]
@david11rsww would you mind sharing the experience how you solve that problem? I faced the same one.
