### ISSUE TITLE
Dead kernel after few seconds

### ISSUE THREAD

**Issue by AmjadKhatabi** [Calysto/matlab_kernel#116]
When I start a new Matlab file in Jupyter the blue sign `connected` appears for a very short time then the kernel dies immediately.
The Matlab API engine is already installed and found in `\Anaconda\Lib\site-packages`. I also tried installing `matlab_kernel` using the `.whl ` and `.tar.gz ` [files](https://pypi.org/project/matlab_kernel/#files) but it didn't solve the problem.
This is what I get in the windows powershell:
![picture1](https://user-images.githubusercontent.com/28957928/47732642-ac049300-dc77-11e8-89f9-37da22715b12.png)

**Comment by blink1073** [comment]
Hi @AmjadKhatabi, it looks like a problem with the matlab engine itself, I'd suggest reinstalling it or reaching out to the Mathworks folks.

**Comment by blink1073** [comment]
Closing as answered, cheers.
