### ISSUE TITLE
Change to new Matlab Engine

### ISSUE THREAD

**Issue by LukasDrude** [Calysto/matlab_kernel#12]
I discovered the Matlab Engine:
http://de.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html

It appears as if this can replace pymatbridge.

Am I right?

**Comment by blink1073** [comment]
It does look that way, eventually, but it also looks like it is only available in the latest version. 



—

**Comment by blink1073** [comment]
The core of the interaction is done through a compiled component, so there's no way to tell how it works.  I'm going to incorporate it.
