### ISSUE TITLE
strange error display: one character per line

### ISSUE THREAD

**Issue by ha7ilm** [Calysto/matlab_kernel#121]
![image](https://user-images.githubusercontent.com/5903408/57126611-dd2c6000-6d8d-11e9-9597-3ce4239bca58.png)

**Comment by blink1073** [comment]
Hi @ha7ilm, what version does `pip show metakernel` give?

**Comment by ha7ilm** [comment]
```
$ pip3 show metakernel
Name: metakernel
Version: 0.21.3
Summary: Metakernel for Jupyter
Home-page: https://github.com/Calysto/metakernel
Author: Steven Silvester
Author-email: steven.silvester@ieee.org
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: ipykernel, pexpect
Required-by: octave-kernel, matlab-kernel

$ pip2 show metakernel
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Name: metakernel
Version: 0.21.2
Summary: Metakernel for Jupyter
Home-page: https://github.com/Calysto/metakernel
Author: Steven Silvester
Author-email: steven.silvester@ieee.org
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: ipykernel, pexpect
Required-by: octave-kernel
```

**Comment by ha7ilm** [comment]
Upgraded to 0.22.1, but it's the same:

![image](https://user-images.githubusercontent.com/5903408/57138410-e54ac680-6db2-11e9-9a78-58e7158a0424.png)

![image](https://user-images.githubusercontent.com/5903408/57138443-f7c50000-6db2-11e9-8af1-b7f08ad4fbd4.png)

**Comment by blink1073** [comment]
Wow, that is odd.  I can't replicate the behavior and I'm not sure what would cause that from looking at the code.

**Comment by ha7ilm** [comment]
I'm also getting this error from Jupyter each time I'm saving the notebook:

![image](https://user-images.githubusercontent.com/5903408/59187442-c12e9200-8b75-11e9-96fb-fbfba1d69251.png)

I think it only happens in case the notebook contains a MATLAB error message.

Probably that's the problematic part of the JSON:

![image](https://user-images.githubusercontent.com/5903408/59187399-a9efa480-8b75-11e9-97e2-a1dadb21cfc8.png)

**Comment by ha7ilm** [comment]
I think my original problem might be related to MATLAB both dumping error messages to `stdout` and throwing them as exceptions:

![image](https://user-images.githubusercontent.com/5903408/59189957-d0184300-8b7b-11e9-82fe-041b80991198.png)
