### ISSUE TITLE
figure properties not working

### ISSUE THREAD

**Issue by neurologic** [Calysto/matlab_kernel#13]
When creating a figure inline (which seems to be the default) using matlab_kernel in a jupyter notebook, the 'Position' property for figure does not change the size of the inline figure.
figure('Position',[0,0,200,10000]) or set(gcf,'Position',[left,bottom,height,width]) is the way figure size is set in Matlab, but this syntax does not seem to be effecting the figure display in the notebook at all.
Any ideas?
Thank you,
Krista

**Comment by blink1073** [comment]
The Matlab kernel is not directly tied to the Matlab plot settings (though that would be a better way to do it).   Right now you have to use `%plot -r <number>`.  https://github.com/Calysto/metakernel/blob/master/metakernel/magics/plot_magic.py#L21

**Comment by neurologic** [comment]
Thank you. That helps. However there are still a lot of parameters for plot control that seem inaccessible with %plot magic. I see that %matplotlib is a built-in magics command for ipython (https://ipython.org/ipython-doc/dev/interactive/magics.html)? Is that the same type of magic command as %plot that can be used similarly? When I try to use %matplotlib like I used %plot it does not seem to be a syntax that makes the matplotlib methods available. 

Basically, I am trying to make a figure with subplots (in a matlab_kernel in iPython) where I can control the size of the figure and the size of the subplots as well as the number of rows/columns. I am plotting multiple objects per subplot so need to be able to use "hold on" so that is does not create a new plot with each line (which is what %plot magic seems to be doing right now).

Thanks again.
I'm obviously new to understanding how the fusion between matlab and ipython works. I appreciate the help. Google searches about this have not gotten me very far.

**Comment by blink1073** [comment]
In this kernel, Matlab is creating an image file, that we then display in the notebook as a static image.  The `%matplotlib` magic is only supported in the main Python kernels.  You should be able to control what happens *within* the figure, since Matlab with save whatever you have drawn.  I do not plan to support any plotting features beyond what is currently available.

**Comment by neurologic** [comment]
OK. Thanks for your help!
I understand a little bit better I think.

**Comment by neurologic** [comment]
Actually that last comment really helped me understand A LOT better. The flow makes sense now about which program is controlling which part of the whole operation. I am able to make the figure show up the way I need to have it in the notebook by first specifying how I want it displayed in the notebook (%plot inline -s 1000,500) and THEN specifying how I want matlab to plot (figure;hold on; subplot; line; ...etc).
It makes sense now.

**Comment by blink1073** [comment]
At the end of each call to the kernel, we ask Matlab to save any open figures to files.  The figures are not shown, but Matplot has still "drawn" everything.  The `%plot` magic is being used to set the file format and resolution of the image that is saved.

**Comment by blink1073** [comment]
Great, please leave this issue open and I'll update the documentation to be a bit clearer.

**Comment by blink1073** [comment]
How is this:

```
A note about plotting.  After each call to Matlab, we ask Matlab to save any 
open figures to image files who's format and resolution are defined using 
the `%plot` magic.  The resulting image is shown inline in the notebook.
```

**Comment by neurologic** [comment]
I think that makes sense. And helps key people to the appropriate places to search for more information about each step of the process.

**Comment by blink1073** [comment]
Great, fixed in the README, thanks for the feedback!
