### ISSUE TITLE
how can I start a matlab embed kernel

### ISSUE THREAD

**Issue by lazywhite** [Calysto/matlab_kernel#137]
[ipython embed kernel example](https://github.com/jupyter/enterprise_gateway/blob/4aff37c637add41d34dd63000fd85ebfbf82a6f2/etc/kernel-launchers/python/scripts/launch_ipykernel.py#L354)

so how to start a matlab embed kernel?

**Comment by blink1073** [comment]
Hi @lazywhite, this kernel does not support embedding.  You might try asking on a Mathworks forum if it is possible to get into an interactive prompt using the MATLAB Engine API for Python.  If so, we could incorporate it here.
