### ISSUE TITLE
Matlab doesn't notice files have changed when executing cells

### ISSUE THREAD

**Issue by beniamino38** [Calysto/matlab_kernel#14]
I am using jupyter-hub and (prerelease) matlab r2015b, on ubuntu 14.04 and Mac OS X 10.10. My workflow is typically:

* Write matlab function in function.m
* Run function in notebook.ipynb using shift-return in a cell which contains the line function(foo, bar)
* Edit function.m
* Run function in notebook.ipynb using shift-return

When I do the last step, I find that the changes to function.m are not noticed by matlab, and it runs a (presumably cached) version of function.m. For example, if function.m contains a print statement, commenting this out has no effect when function.m is run from the notebook.

I have worked around this by adding an ls() to the first line of do_execute_direct, but obviously this is not the right fix:
```
    def do_execute_direct(self, code):
        self._matlab.run_code("ls;")
```

**Comment by auneri** [comment]
This might be related to the [rehash function](http://www.mathworks.com/help/matlab/ref/rehash.html), rather than a problem in matlab_kernel.

**Comment by beniamino38** [comment]
auneri: Can you expand what you mean a bit? I only have this problem from within a notebook, so it doesn't seem to be a general matlab problem

**Comment by blink1073** [comment]
I think what we need to do is call `rehash` before each `run_code` (in pymatbridge), since apparently this is done from the Matlab command window, but not when run remotely.

**Comment by blink1073** [comment]
See https://github.com/arokem/python-matlab-bridge/pull/206.

**Comment by blink1073** [comment]
Closing as fixed by newer releases, feel free to reopen if you disagree.
