### ISSUE TITLE
Will there be a conda version ?

### ISSUE THREAD

**Issue by integzz** [Calysto/matlab_kernel#143]

**Comment by blink1073** [comment]
Hi @integzz, I don't have the bandwidth to set it up, but would happy to be a maintainer if someone else wants to contribute the recipe to conda-forge.

**Comment by integzz** [comment]
Fully understand. Thank you for the package !

**Comment by blink1073** [comment]
Cheers!

**Comment by stanmart** [comment]
Hi! I can try setting up a conda-forge recipe if you'd like.
