### ISSUE TITLE
Kernel keeps restarting in Jupyterlab

### ISSUE THREAD

**Issue by rongmu** [Calysto/matlab_kernel#144]
The matlab kernel keeps restarting every time I attempt to run a code cell in Jupyterlab.
The kernel works fine with `jupyter console --kernel matlab` though.

MATLAB 2018b
jupyterlab v2.1.5
matlab-kernel v0.16.9

![2020-07-10 150355](https://user-images.githubusercontent.com/1129506/87121891-c2714780-c2be-11ea-9d64-d6bfdee21c71.png)

**Comment by blink1073** [comment]
HI @rongmu, if  you run as `jupyter lab --debug`, do you get an error when the kernel starts in the terminal?  If so, can you please paste that here?

**Comment by rongmu** [comment]
@blink1073 Thank you for the reply!
I don't know the cause but the problem is apparently resolved after a reboot of my Ubuntu machine 😅.
I will close this issue.
