### ISSUE TITLE
Conda recipe

### ISSUE THREAD

**Issue by stanmart** [Calysto/matlab_kernel#151]
Hi!,

If I understand correctly (based on a closed issue) you would be okay with having your package on conda-forge. I took a stab at it, here is the PR: [conda-forge/staged-recipes/pull/13265](https://github.com/conda-forge/staged-recipes/pull/13265)

If you like it, please write a comment under the PR that you are okay with being listed as a maintainer (apparently it is a requirement for new recipes). If there is anything which does not seem right, let me know and I'll fix it. If I misunderstood you and you would not like to have your package on conda-forge, please let me know that as well, and I'll delete this PR.

**Comment by blink1073** [comment]
Thanks for doing that!
