### ISSUE TITLE
Kernel dies

### ISSUE THREAD

**Issue by outlace** [Calysto/matlab_kernel#16]
I try to create a new ipython notebook with the matlab kernel, it says connected for a second then it says the kernel dies. I've installed it correctly with all dependencies as far as I can tell. On Mac osx

**Comment by outlace** [comment]
Fixed. pymatbridge points to wherever typing "matlab" into the terminal returns. So my path to matlab was not properly set.

**Comment by blink1073** [comment]
Great, glad it is working for you!
