### ISSUE TITLE
every fprintf creates separate output cell

### ISSUE THREAD

**Issue by allefeld** [Calysto/matlab_kernel#164]
I use `fprintf` to print information in a formatted way. The problem is that each `fprintf` creates a new output cell, so that several lines of text, which in Matlab itself would appear contiguous, are broken up.

Is there a way to make sure that text output (stdout, stderr) created in one code cell is collected and put into one output cell?

Example:

Matlab code cell:

```{matlab}
fprintf('First line\n')
fprintf('Second line\n')
fprintf('Third line ')
fprintf('in two parts\n')
```

Output:

``````
::: {.cell-output .cell-output-stdout}
```
First line
```
:::

::: {.cell-output .cell-output-stdout}
```
Second line
```
:::

::: {.cell-output .cell-output-stdout}
```
Third line 
```
:::

::: {.cell-output .cell-output-stdout}
```
in two parts
```
:::
``````

Rendered as:

```
First line
```

```
Second line
```

```
Third line 
```

```
in two parts
```

In Matlab itself, the output appears as:

```
First line
Second line
Third line in two parts
```

**Comment by allefeld** [comment]
Sorry, this seems to occur only in combination with Quarto:
https://github.com/quarto-dev/quarto-cli/issues/4968

**Comment by cscheid** [comment]
(quarto dev here) For what's worth, quarto's execution of notebooks happens through the [`nbclient` library](https://github.com/jupyter/nbclient), so that might be a direction to track down the issue. (I don't have access to matlab so I can't help further, sorry.)
