### ISSUE TITLE
Can't use matlab_kernel

### ISSUE THREAD

**Issue by yarmenti** [Calysto/matlab_kernel#17]
Hi,

I successfully installed the package and currently using a W8 machine with Matlab 2014 and IPython 4.0. Nevertheless, I can't find the Matlab kernel when trying ipython kernelspec list.
Did I miss something?

Thanks,

**Comment by yarmenti** [comment]
Hi again;

I succeed install and use it, but it seems that the pip install is not properly working.
Cheers,

**Comment by blink1073** [comment]
Just to follow up, I released a version that will properly pip install.  Thanks for the heads up!
