### ISSUE TITLE
dead kernel 

### ISSUE THREAD

**Issue by nasbelyakova** [Calysto/matlab_kernel#19]
I installed anaconda, metakernel, pymatbridge, matlab_kernel but whenever I try to launch Matlab kernel in ipython notebook it just does not starts. Only dives a 'Kernel died, restarting' message.  
What is wrong? 
It is great project and I was really exited to be able to run matlab code in python notebook.

**Comment by dsblank** [comment]
Do you get an error message in the console?

**Comment by nasbelyakova** [comment]
Something like 'Could no find file specified'

**Comment by blink1073** [comment]
@nasbelyakova, it sounds like it cannot find your `matlab` executable.  You can create `MATLAB_EXECUTABLE` environment variable to point to it.

**Comment by dsblank** [comment]
@blink1073 Did you know that you can set environment variables in the kernel.json? It looks like:

https://github.com/Calysto/calysto_processing/blob/master/setup.py#L15

Just FYI.

**Comment by blink1073** [comment]
That would pair nicely with the assistant to the Kernel manager: https://github.com/minrk/a2km

**Comment by nasbelyakova** [comment]
Thanks, but this does not works.

**Comment by nasbelyakova** [comment]
Do I need to have Matlab installed to use notebook kernel?

**Comment by dsblank** [comment]
@nasbelyakova Yes. Or you can use the Octave kernel, which requires the open source alternative, Octave:

https://github.com/calysto/octave_kernel

**Comment by nasbelyakova** [comment]
Than sure it did not worked.
 LOL
