### ISSUE TITLE
dead kernel

### ISSUE THREAD

**Issue by jsudbang** [Calysto/matlab_kernel#21]
I use Jupyter and have MATLAB on my computer. I installed pymatbridge and matlab_kernel but whenever I to launch the Matlab kernel in ipython notebook it dies immediately.

I think that probably it has something to do with my MATLAB executable path? I'm confused by this sort of thing.

**Comment by blink1073** [comment]
Yes, you should be able to type `matlab` from the same command prompt as where you launch the notebook from, or, you can also se the `MATLAB_EXECUTABLE` environment variable.

**Comment by jsudbang** [comment]
I'm not totally sure how to do that, any advice?
I tried adding the MATLAB executable as follows:
MATLAB_EXECUTABLE=/usr/bin/matlab; 

but that didn't work...I'm not actually sure where my MATLAB is installed. Do you know how I would find this?

**Comment by blink1073** [comment]
How do you normally run Matlab?  What operating system are you on?

**Comment by jsudbang** [comment]
I'm on Mac OSX. Normally I just start up MATLAB from my applications folder:

Would this be the executable?
/Applications/MATLAB_2015b.app/bin/matlab

**Comment by blink1073** [comment]
That looks right.  You can add this to your ~/.bash_profile:

export MATLAB_EXECUTABLE=/Applications/MATLAB_2015b.app/bin/matlab

**Comment by jsudbang** [comment]
Maybe that's not my issue. I'm getting thousands of lines of errors in my command line as jupiter tries to restart the kernel. I'm not even sure what to copy to help you diagnose the problem. I'm getting things that look like this over and over:

/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc in _execute_child(self=<subprocess.Popen object>, args=['/Applications/MATLAB_2015b.app/bin/matlab', '-e'], executable='/Applications/MATLAB_2015b.app/bin/matlab', preexec_fn=None, close_fds=False, cwd=None, env=None, universal_newlines=False, startupinfo=None, creationflags=0, shell=False, to_close=set([55, 57]), p2cread=None, p2cwrite=None, c2pread=55, c2pwrite=56, errread=57, errwrite=58)
   1333                         raise
   1334                 child_exception = pickle.loads(data)
-> 1335                 raise child_exception
        child_exception = OSError(2, 'No such file or directory')
   1336 
   1337 

OSError: [Errno 2] No such file or directory

**Comment by jsudbang** [comment]
Also warnings: 
/usr/local/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/usr/local/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
---------------------------------------------------------------------------

**Comment by jsudbang** [comment]
Similar issue for Julia was seen here, but I'm not sure how this would translate to this kernel:

https://github.com/JuliaLang/IJulia.jl/issues/117

**Comment by jsudbang** [comment]
OK, sorry, I messed up the MATLAB executable line.

Now it's almost working but I'm getting this:

[I 17:17:22.077 NotebookApp] Kernel started: 92ee5d5d-612c-4c6a-a672-4c46144a69a9
/usr/local/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/usr/local/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
[W 17:17:32.139 NotebookApp] Timeout waiting for kernel_info reply from 92ee5d5d-612c-4c6a-a672-4c46144a69a9

**Comment by jsudbang** [comment]
ok, nevermind MATLAB seems to be working now. Thanks for your help!

**Comment by blink1073** [comment]
Cheers, enjoy!
