### ISSUE TITLE
kernel died error

### ISSUE THREAD

**Issue by HamtaroWarrior** [Calysto/matlab_kernel#25]
When I try to launch the Matlab kernel, I have the following output

    $ipython qtconsole --kernel=matlab_kernel
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/usr/lib/python2.7/site-packages/matlab_kernel.py", line 106, in <module>
        from ipykernel.kernelapp import IPKernelApp
      File "/usr/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 97, in <module>
        ConnectionFileMixin):
      File "/usr/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 518, in __new__
        return super(MetaHasTraits, mcls).__new__(mcls, name, bases, classdict)
    TypeError: Error when calling the metaclass bases
        metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

I have the same error with `console` instead of `qtconsole` and with `notebook` when launching matlab's kernel. When using the jupyter notebook, I have a "Kernel Died" error.

I'm on Unix (Fedora 23)

    $ python --version
    Python 2.7.10

    $ ipython --version
    3.2.1

    $ echo $MATLAB_EXECUTABLE
    /usr/bin/matlab

(I also tried with `/usr/local/MATLAB/R2015b/bin/matlab`)

`metakernel`, `pymatbridge`, `matlab_kernel` and `jupyter` are installed and up to date via `pip`

**Comment by dsblank** [comment]
Something must have changed over at https://github.com/ipython/ipykernel

@minrk, do you have an idea? Or know who might?

**Comment by blink1073** [comment]
It looks like you're mixing `ipykernel`, which is a Jupyter 4.0 library, with `IPython 3.0`.  I'd say either remove `ipykernel` or upgrade to `IPython 4.0`.

**Comment by HamtaroWarrior** [comment]
upgrading iPython to the 4.0 version did the work, I'm closing the issue. Thank you

**Comment by dsblank** [comment]
@blink1073 Good catch! Thanks for the feedback, @HamtaroWarrior

**Comment by dsblank** [comment]
Fixed README.
