### ISSUE TITLE
Jupyter - MatLab Kernel

### ISSUE THREAD

**Issue by gmur24** [Calysto/matlab_kernel#26]
Hi - I can now see Matlab as one of the kernels. When I tried to create a new file, the kernel died and the Matlab software kept popping up until I close the kernel. Please help.

**Comment by blink1073** [comment]
What operating system are you using?

**Comment by gmur24** [comment]
Windows

**Comment by blink1073** [comment]
What version?

**Comment by gmur24** [comment]
sorry windows 10

**Comment by blink1073** [comment]
hmm, I don't have access to Windows 10.  Does the same thing happen if you try to use `pymatbridge` by itself?  https://arokem.github.io/python-matlab-bridge/

**Comment by gmur24** [comment]
you mean when I installed pymatbridge?

**Comment by blink1073** [comment]
I mean using pymatbridge from a python console.

**Comment by gmur24** [comment]
let me try that

**Comment by gmur24** [comment]
nope

**Comment by blink1073** [comment]
same issue?

**Comment by blink1073** [comment]
See https://github.com/arokem/python-matlab-bridge/issues/226 and https://github.com/arokem/python-matlab-bridge/issues/220

**Comment by gmur24** [comment]
nothing still

**Comment by blink1073** [comment]
Sorry, I'm not sure what exactly could have changed between Windows versions, it may require a new build of the messenger MEX for pymatbridge.

**Comment by blink1073** [comment]
Closing as the issue is with pymatbridge, not this library.
