### ISSUE TITLE
Matlab Kernel Dies

### ISSUE THREAD

**Issue by Chibuikem709** [Calysto/matlab_kernel#27]
So my matlab kernel in Jupyter keeps dying. I have installed pymatbridge, metakernel and matlab_kernel. I also point to the executable:
 export MATLAB_EXECUTABLE=/Applications/MATLAB_2015b.app/bin/matlab
 and it works. But then when I exit Jupyter, close the terminal, or log/shut down my computer, I get the same error 
![image](https://cloud.githubusercontent.com/assets/16184620/11644097/1514110c-9d17-11e5-8f95-42a030970855.png)
![image](https://cloud.githubusercontent.com/assets/16184620/11644106/2427b7de-9d17-11e5-8457-38748bf40f5c.png)

must I reinstall these things before every use?

**Comment by blink1073** [comment]
Hi @Chibuikem709, if you put that export line in your `~/.bash_profile`, it should work every time.

**Comment by Chibuikem709** [comment]
How do I do that?

**Comment by blink1073** [comment]
From the command line: `echo "export MATLAB_EXECUTABLE=/Applications/MATLAB_2015b.app/bin/matlab" >> ~/.bash_profile`

**Comment by Chibuikem709** [comment]
Oh ok! I had to modify the statement slightly to 
echo "export MATLAB_EXECUTABLE=/Applications/MATLAB_R2015b.app/bin/matlab" >> ~/.bash_profile

But it looks to be working! Ill keep you posted on any new development.

**Comment by blink1073** [comment]
Great, glad to hear it.

**Comment by blink1073** [comment]
Closing as fixed, feel free to reopen if you disagree.
