### ISSUE TITLE
Errors in starting Matlab kernel (Windows 8.1)

### ISSUE THREAD

**Issue by hpay** [Calysto/matlab_kernel#28]
What I've done: I have installed the following and am successfully using a jupyter notebook with standard python kernel:
~~~
$ pip install jupyter
$ pip install pymatbridge
$ pip install matlab_kernel
~~~

I've added an Environment Variable to my Matlab path (Windows 8.1): (Under Edit System Variables, Variable name is:MATLAB_EXECUTABLE and Variable Value is C:\Program Files\MATLAB\Matlab2013a\bin\matlab. 

**The problem: When I try using the Matlab kernel in Jupyter, it opens a desktop instance of Matlab, with the following errors in the command line:**
~~~
C:\Program Files\MATLAB\R2013a\toolbox\local\pathdef.m: Cannot open file: permission denied.
Warning: MATLAB did not appear to successfully set the search path. To recover for this session of MATLAB, type "restoredefaultpath;matlabrc". To find out how to avoid this warning the next time you start MATLAB, type "docsearch problem path" after recovering for this session.
Warning: Duplicate directory name: C:\Program Files\MATLAB\R2013a\toolbox\local
Warning: Initializing Handle Graphics failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should be resolved as soon as possible.  Error detected was:
MATLAB:undefinedVarOrClass
Undefined variable "graphics" or class "graphics.internal.initializeMATLABRoot".
Warning: Initializing Java preferences failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should be resolved as soon as possible.  Error detected was:
MATLAB:UndefinedFunction
Undefined function 'usejava' for input arguments of type 'char'.
> In matlabrc at 110 
Warning: Failed to add default profiler filters.
> In matlabrc at 149 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.mathworks.mlwidgets.graphics.ModelStateFactory.createNoSelectionModelState(ModelStateFactory.java:242)
	at com.mathworks.mlwidgets.graphics.PlotToolSetFactory$3.parseComplete(PlotToolSetFactory.java:127)
	at com.mathworks.mlwidgets.graphics.ModelStateFactory$ProductInfoListener$1$1.run(ModelStateFactory.java:1023)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
~~~
Matlab start fine when I click on the normal shortcut to start it directly.
And this is the output in the command window:
~~~
[I 19:53:24.133 NotebookApp] Kernel started: 362908f1-a163-4172-994b-fed8c275e10
b
C:\Anaconda3\lib\site-packages\IPython\nbformat.py:13: ShimWarning: The `IPython
.nbformat` package has been deprecated. You should import from nbformat instead.

  "You should import from nbformat instead.", ShimWarning)
[IPKernelApp] ERROR | Can't load 'C:\Anaconda3\lib\site-packages\metakernel\magi
cs\shell_magic.py': error: The command was not found or was not executable: bash
.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
[W 19:53:34.159 NotebookApp] Timeout waiting for kernel_info reply from 362908f1
-a163-4172-994b-fed8c275e10b
~~~
(Truncated huge amount of output, then)
~~~
ValueError: MATLAB failed to start
~~~

Any idea what's going on? Have tried figuring out how to fix the pathdef permission error but not sure what to change..I already have administrator rights, but it is a work-owned computer so maybe they have restricted something.

I am new to python and jupyter so apologies if I am missing something basic. Excited to try this out!

**Comment by blink1073** [comment]
Hmm, what is the actual output of `echo %MATLAB_EXECUTABLE%`?  It looks like it only picked up the path up to the first space character.

**Comment by hpay** [comment]
~~~
C:\Users\hpay4_000>echo %MATLAB_EXECUTABLE%
C:\Program Files\MATLAB\R2013a\bin\matlab
~~~

So it seems to be picking up the space ok? Matlab seems to start (a window
opens) but prints the errors about pathdef permissions I posted above.

Thanks!

**Comment by blink1073** [comment]
Are you able to run `pymatbridge` itself?

```python
from pymatbridge import Matlab
mlab = Matlab(r'C:\Program Files\MATLAB\R2013a\bin\matlab')
mlab.start()
print(mlab.run_code('a=1;'))
```

**Comment by hpay** [comment]
I tried running pymatbridge itself as you described (assuming you mean
running that from ipython, And I had to change this line: mlab = Matlab(r'C:
\Program Files\MATLAB\R2013a\bin\matlab')
 to mlab = Matlab()  -- can't get it to work with the pathname specified
there)
 - works, opens a command window for matlab and prints output! (Also went
through the instructions for installing pymatbridge again)

But now a different error message.

When I start jupyter notebook:
'''
C:\Dropbox>jupyter notebook
[W 17:58:02.447 NotebookApp] Permission to listen on port 8888 denied
'''

The web page opens; then if I select a Matlab kernel, the kernel tries to
start repeatedly and fails.
I don't know if all the output in the command prompt would be helpful, this
is just what it says at the end:
'''
PermissionError: [WinError 5] Access is denied
[W 18:04:13.314 NotebookApp] KernelRestarter: restart failed
[W 18:04:13.314 NotebookApp] Kernel df903dda-90ca-473e-9529-e40bbd016025
died, r
emoving from map.
ERROR:root:kernel df903dda-90ca-473e-9529-e40bbd016025 restarted failed!
[W 18:04:13.333 NotebookApp] Kernel deleted before session
[W 18:04:13.334 NotebookApp] 410 DELETE
/api/sessions/c2e146d0-0427-4336-b5e0-d8
148a44c40e (::1) 2.02ms referer=
http://localhost:8889/notebooks/Untitled2.ipynb?
kernel_name=matlab_kernel
'''

[image: Inline image 1]

**Comment by blink1073** [comment]
Hmm, can you try editing your `matlab_kernel.py` file as follows?
You can find it using `python -c "import matlab_kernel; print(matlab_kernel.__file__)"`:

```diff
diff --git a/matlab_kernel.py b/matlab_kernel.py
index ba2cda7..356ae0c 100644
--- a/matlab_kernel.py
+++ b/matlab_kernel.py
@@ -28,10 +28,7 @@ class MatlabKernel(MetaKernel):

     def __init__(self, *args, **kwargs):
         super(MatlabKernel, self).__init__(*args, **kwargs)
-        executable = os.environ.get('MATLAB_EXECUTABLE', 'matlab')
-        subprocess.check_call([executable, '-e'], stdout=subprocess.PIPE,
-                              stderr=subprocess.PIPE)
-        self._matlab = Matlab(executable)
+        self._matlab = Matlab()
         self._matlab.start()

     def get_usage(self):
```

**Comment by blink1073** [comment]
Closing due to lack of response, please feel free to reopen.
