### ISSUE TITLE
Matlab kernel does not get added to Jupyter on W7

### ISSUE THREAD

**Issue by rugge88** [Calysto/matlab_kernel#29]
Hello,
I'm trying to install matlab kernel. I set the environment variable:
echo %MATLAB_EXECUTABLE%
C:\Progra~1\MATLAB\R2014a\bin\matlab
But when I run ipython notebook matlab does not appear into the list of available kernels

Reading the issues I also tried to check:
from pymatbridge import Matlab
mlab = Matlab(r'C:\Program Files\MATLAB\R2014a\bin\matlab')
mlab.start()
print(mlab.run_code('a=1;'))

but if I put mlab = Matlab() the connection is correctly established. 

I am running w7 64bit, I used the alias Progra~1 for Program Files to avoid space issues

**Comment by blink1073** [comment]
Hi @rugge88, can you please try `pip install -U matlab_kernel` and see if it shows up in the list of kernels, I just released a new version this past weekend (0.6.10).

**Comment by rugge88** [comment]
It says "requirement already up-to-date: matlab_kernel in ...."

**Comment by blink1073** [comment]
Perhaps you are running the notebook from a different python environment than where you installed the kernel?

**Comment by blink1073** [comment]
Hi @rugge88, this has been addressed in newer releases, please see the new install instructions.  I am closing as fixed, please feel free to reopen if you disagree.
