### ISSUE TITLE
First cell run seems to always return an error

### ISSUE THREAD

**Issue by arokem** [Calysto/matlab_kernel#3]
Specifically, it returns this one:      

    'NoneType' object has no attribute 'split'

When I rerun it, no problem. FWIW, this doesn't seem to be an issue when running the matlab_magic in pymatbridge.

**Comment by blink1073** [comment]
What did you type?  Are you using 0.4?

**Comment by arokem** [comment]
I was wrong - it does execute, but also throws this error:

http://nbviewer.ipython.org/gist/arokem/0fd0e00827503c397123

Previously, I was running statements with semi-colons, so I thought I was
just getting the error.

Yes - this is on 0.4, I believe. Is it possible that  I need to erase any
config files after upgrading with pip? I have not done that.

**Comment by blink1073** [comment]
I don't see this error using IPython 3, development version of pymatbridge, and development version of this repo...

**Comment by blink1073** [comment]
How about now?

**Comment by blink1073** [comment]
59150a235736eec06cab6e26e054a41bd808f234 should address your issue.

**Comment by arokem** [comment]
Yes - after reinstalling both matlab_kernel and metakernel from the current
master branches, that does seem to go away. Thanks!
