### ISSUE TITLE
is Auto-complete a feature

### ISSUE THREAD

**Issue by luli11** [Calysto/matlab_kernel#31]
tried to tab auto-complete matlab commands/variable  and receive no response, wonder if it is a implemented feature or I ran into  issues with my installation.

Many thanks

**Comment by blink1073** [comment]
Hi @luli11, it is not implemented because I could not find a function in Matlab to query for completions given a substring.

**Comment by brunobeltran** [comment]
Fixed by #44 and #47

**Comment by blink1073** [comment]
Indeed.
