### ISSUE TITLE
Timeout waiting for kernel_info

### ISSUE THREAD

**Issue by mgorjis** [Calysto/matlab_kernel#33]
Hi

I am trying to set up Matlab kernel on a Mac device. I had installed on several windows devices and I hadn't have any issue. But in the Mac, I installed pymatbridge and ran: ( I have matlabr2015b)

_pip install matlab_kernel
python -m matlab_kernel.install
MATLAB_EXECUTABLE=/usr/bin/matlab
export MATLAB_EXECUTABLE=/Applications/MATLAB_2015b.app/bin/matlab
ipython notebook --kernel=matlab_kernel_

The Matlab is added to the lists of my Kernels in the notebook. When I choose matlab from the list of kernels, however, the kernel cannot be started, and I see the following  time out error. 

[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook`... continue in 5 sec. Press Ctrl-C to quit now.
[W 15:48:42.495 NotebookApp] Unrecognized alias: '--kernel=matlab_kernel', it will probably have no effect.
[I 15:48:42.559 NotebookApp] Serving notebooks from local directory: /Users/mgorjise
[I 15:48:42.559 NotebookApp] 0 active kernels 
[I 15:48:42.559 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 15:48:42.559 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 15:48:45.554 NotebookApp] Kernel started: f6adac45-106d-4ec9-9e98-307da311494a
/usr/local/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
/bin/sh: /usr/bin/matlab: No such file or directory
[W 15:48:55.629 NotebookApp] Timeout waiting for kernel_info reply from f6adac45-106d-4ec9-9e98-307da311494a

Does anyone has any idea? Thank you.

**Comment by JohnCosnett** [comment]
remove the "MATLAB EXECUTABLE = usr/biin/matlab

and paste this into your terminal then restart it.

   echo “export MATLAB_EXECUTABLE=/Applications/MATLAB_2015b.app/bin/matlab” >> ~/.bash_profile

check your  with
    open ~/.bash_profile

**Comment by mgorjis** [comment]
It worked! Thank you very much.

**Comment by blink1073** [comment]
Great!  Not sure why just exporting it from the command line does not work...

**Comment by mgorjis** [comment]
sometimes it worked only by

export MATLAB_EXECUTABLE=/Applications/MATLAB_2015b.app/bin/matlab
