### ISSUE TITLE
user-defined functions ?

### ISSUE THREAD

**Issue by JohnCosnett** [Calysto/matlab_kernel#35]
for instance

    function out = square(x)

    out = x^2

    end

is there a way of defining matlab functions?

-----

![screen shot 2016-02-28 at 20 07 25](https://cloud.githubusercontent.com/assets/15061801/13381564/1f2bc636-de57-11e5-8416-9ade14c08d2d.png)

**Comment by blink1073** [comment]
Yes, as long as the m-file is on your Matlab path (you may need to use `addpath`).

**Comment by blink1073** [comment]
Closing as fixed, please feel free to reopen if you disagree.

**Comment by daquintero** [comment]
Is there no way to do this within the jupyter kernel and what would be the reason why?

**Comment by SicariusNoctis** [comment]
@daquintero See [here](https://stackoverflow.com/a/49223171/365102):

```matlab
%%file my_func.m

function y = my_func(x)
    y = x;
end
```
