### ISSUE TITLE
Symbolic math errors

### ISSUE THREAD

**Issue by karldw** [Calysto/matlab_kernel#37]
Using symbolic variables throws an error in Jupyter.

For example, the command `syms x;` works fine in a normal matlab command prompt, but in Jupyter I get the error `Invalid variable name "matrix(0, 1, [])" in ASSIGNIN.`

Is it possible to fix this without too grand a hassle?

**Comment by blink1073** [comment]
This sounds like a limitation of the JSON parser used by `pymatbridge`.  Do you mind trying you code using just `pymatbridge` and see if you get the same error?

Here's and example: https://github.com/arokem/python-matlab-bridge/blob/master/pymatbridge/examples/pymatbridge.ipynb

**Comment by karldw** [comment]
You're right:

```python
>>> import pymatbridge as pymat
/home/karl/.conda/lib/python3.5/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
>>> matlab = pymat.Matlab()
>>> matlab.start()
Starting MATLAB on ZMQ socket ipc:///tmp/pymatbridge-b0341d2a-d1a4-42fd-a2a7-60aed0973e70
Send 'exit' command to kill the server
.......MATLAB started and connected!
<pymatbridge.pymatbridge.Matlab object at 0x7f6508fb5780>
>>> res_dict = matlab.run_code('syms x;')
>>> res_dict
{'content': {'stdout': 'Invalid variable name "matrix(0, 1, [])" in ASSIGNIN.'}, 'success': False, 'result': ''}
```

**Comment by blink1073** [comment]
Moved to https://github.com/arokem/python-matlab-bridge/issues/231.

**Comment by karldw** [comment]
Cool, thank you.
