### ISSUE TITLE
Install matlab_kernel in windows 10

### ISSUE THREAD

**Issue by adowaconan** [Calysto/matlab_kernel#38]
I followed the step to install matlab_kernel via command prompt:
    activate conda-py35
    pip install matlab_kernel
But when I check the kernels:
    ipython kernel list
It is not there. Is there any steps I missed?

**Comment by dsblank** [comment]
Sounds like you might have two ipython's installed, or using old commands. Some things to try:

`which ipython`

Is that coming from your conda install?

`jupyter kernelspec list`

That is the new method to see installed kernels.

**Comment by adowaconan** [comment]
Doug, Thanks for the reply.I have two pythons installed, but I rarely use python 2. Both pythons are conda pythons. I usually activate python 3 via command prompt using "activation" in the scrtipts folder. I think I install matlab_kernel to the conda-python 3 because that is also how I install R_kernel. However, matlab_kernel did not show up in the new script option. So I think I must miss steps or could be the way I install the kernel. Ning                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Doug BlankSent: Saturday, April 9, 2016 10:39To: Calysto/matlab_kernelReply To: Calysto/matlab_kernelCc: adowaconanSubject: Re: [Calysto/matlab_kernel] Install matlab_kernel in windows 10 (#38)Sounds like you might have two ipython's installed, or using old commands. Some things to try:

which ipython

Is that coming from your conda install?

jupyter kernelspec list

That is the new method to see installed kernels.

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by adowaconan** [comment]
I uninstalled conda-python 2 and re-installed jupyter, matlab_kernel, but I still don't see matlab_kernel appear in my kernel list. 

Ning

**Comment by blink1073** [comment]
Hi @adowaconan, it looks like you need to run `python -m matlab_kernel.install`, which installs the kernelspec itself.

**Comment by blink1073** [comment]
Closing as fixed in with the new install instructions, feel free to reopen if you are still having problems.

**Comment by RoyiAvital** [comment]
Hi,

How can I manually install it on [WinPython](https://winpython.github.io/)?
It means I have Python (With iPython working) yet not installed (Portable) or registered.

How can I make it work (MATLAB is installed regularly)?

**Comment by blink1073** [comment]
Hi @RoyiAvital, you should be able to install it from a Command Window as follows:

```
pip install matlab_kernel
python -m matlab_kernel.install
```

**Comment by RoyiAvital** [comment]
@blink1073 , I think if I install Python using WinPython in Portable Mode Python isn't registered into System Variables hence this won't work form command line.
Hence I asked how to install it manually (No scripts, doing everything by hand).

Thank You.

**Comment by blink1073** [comment]
The above commands should work in the winpython command prompt per https://github.com/winpython/winpython/wiki/Installing-Additional-Packages.

**Comment by RoyiAvital** [comment]
@blink1073 , That's nice.

I will give it a try.

Thank You.

P. S.
Installing it won't do any registration of variable to Windows, right?
I'd like to keep my Python installation completely portable.

**Comment by blink1073** [comment]
There is the bit about installing the Matlab engine itself, instructions for that are here: https://www.mathworks.com/help/matlab/matlab_external/install-matlab-engine-api-for-python-in-nondefault-locations.html.

**Comment by RoyiAvital** [comment]
Could you write "Release Notes" for each release in the Releases Page?

Thank You.
