### ISSUE TITLE
Native MATLAB Python interaction API

### ISSUE THREAD

**Issue by anntzer** [Calysto/matlab_kernel#39]
Recent versions of MATLAB (since 2015a) ship with a python interaction module (http://www.mathworks.com/help/matlab/matlab-engine-for-python.html).  I had modified an old version of `matlab_kernel` to use either the official module, if present (basically passing everything to MATLAB's `eval`), or `pymatbridge` otherwise:

https://gist.github.com/anntzer/e4fafaa4fb1136d6b93d32cba8f29f9f

This is based off 9c7c2f4 so a little bit of work may be needed to rebase this on master.  Also, I stripped out the figure interaction code because I personally prefer having the windows pop out but it should be easy to restore it; I guess at the end of the day the "best" way to handle this is with another option for "%plot" that allows for individual windows.

**Comment by blink1073** [comment]
Awesome, thanks @anntzer, I should be able to fold this in this weekend.

**Comment by blink1073** [comment]
I released v0.9 which adds your patch and allows you to specify `%plot foo` to specify a backend other than inline, so you can use `%plot native` in Matlab to get your individual windows.

**Comment by anntzer** [comment]
Thanks for the quick reply! There's a few issues with your integration.

1)
```
        if matlab_native:
            self._engine = matlab.engine.start_matlab()
            self.name = 'matlab'
        if 'OCTAVE_EXECUTABLE' in os.environ: # <- should be "elif", otherwise matlab_native is always overriden
            self._engine = Octave(os.environ['OCTAVE_EXECUTABLE'])
```

2) The (original) native matlab kernel does not return a `resp = {"success": ..., "content": {"stdout": ..., "figures": ...}}` dict, but rather prints stdout to... stdout and raises an exception on failure.  So you should re-create the dict as appropriate (see how I capture stdout in `_run_native`).  It may be possible to capture all open windows as well to populate `resp["content"]["figures"]`.

**Comment by auneri** [comment]
#40 should fix first item, while #41 partially addresses the second item.

**Comment by blink1073** [comment]
@anntzer, this should be addressed in the latest release, can you confirm?

**Comment by anntzer** [comment]
Works well, thanks.
There remains some issues on Py3.5, but MATLAB doesn't officially support it so I won't bother you about it either.

**Comment by blink1073** [comment]
Great!

**Comment by anntzer** [comment]
Could we make pymatbridge an optional ("extras") dependency?  (Perhaps add an explicit exception at import time if neither the native engine nor pymatbridge are available.)

**Comment by blink1073** [comment]
I do not actually have a copy of Matlab, so it is making the maintenance of this library untenable.  My inclination is to drop support of pymatbridge altogether and rely on others for updates/enhancements.
