### ISSUE TITLE
Cannot create output file '/tmp/MatlabData/foo.png'

### ISSUE THREAD

**Issue by dolpang2** [Calysto/matlab_kernel#45]
I installed jupyterhub (not jupyter) and tested plotting.

Environment is Ubuntu 14.04 and Matlab 2015

When draw plot, I got message

Cannot create output file '/tmp/MatlabData/MatlabFig001.png'.

How to solve it?

**Comment by dsblank** [comment]
Do you have the full log error, or stack trace?

**Comment by dolpang2** [comment]
![image](https://cloud.githubusercontent.com/assets/9076745/14983535/0214870e-1179-11e6-8c67-658d62a0a62c.png)

Unfortunately... this message is all.

**Comment by blink1073** [comment]
Hi @dolpang2, can you please try putting `%plot -f svg` at the start of the cell?

**Comment by dolpang2** [comment]
@blink1073 I tried, but same error occured.
![image](https://cloud.githubusercontent.com/assets/9076745/14987993/ce9ecd6c-118c-11e6-9927-d5f44d7b32ec.png)

**Comment by dsblank** [comment]
On jupyterhub, each user should have their own temp directory for creating images. Could another user have already created a file/directory named this?

**Comment by dolpang2** [comment]
@dsblank Thanks! Your comment is very helpful.
My temporary solution is
`chmod 777 -R /tmp/MatlabData`

**Comment by blink1073** [comment]
See https://github.com/arokem/python-matlab-bridge/issues/236.

**Comment by auneri** [comment]
Heads up, if a fix is implemented in python-matlab-bridge, it would need to be applied for the native MATLAB interface as well, since [the same logic was used here](https://github.com/Calysto/matlab_kernel/blob/master/matlab_kernel/kernel.py#L68).

**Comment by anntzer** [comment]
Closing as pymatbridge is no longer supported.  Please request a reopen if still applicable for the native engine.
