### ISSUE TITLE
Support kernel interrupts

### ISSUE THREAD

**Issue by andystoneucl** [Calysto/matlab_kernel#5]
Very promising project, I love being able to use Matlab through Jupyter, but it appears that the 'interrupt kernel' button doesn't do anything (on Windows 8.1 at least).

If I forget a semicolon in a big Matlab loop then I can hit ctrl+C in the normal Matlab command window to stop the loop (otherwise it takes forever writing massive quantities of output to the screen).  Without the interrupt kernel option the only options you are left with are waiting for it to eventually finish or killing the whole kernel - which is undesirable if you then have to re-run loads of slow stuff to get back to the same point.

Had a quick look at the ipython/Jupyter documentation but couldn't see where kernel interrupts might need to be implemented.

**Comment by blink1073** [comment]
Hi @andystoneucl, thanks for your interest.  I think the ability to interrupt the Matlab process is actually something that should go in `pymatbridge`, and may not work on Windows.  Once that is in place, we can use that functionality here.

**Comment by blink1073** [comment]
See https://github.com/arokem/python-matlab-bridge/issues/164.

**Comment by andystoneucl** [comment]
Thanks.  Make sense that it belongs in `pymatbridge`.  

Hopefully it's possible to implement somehow - I don't know if the mechanics of how Jupyter connects to Matlab is fundamentally different to how it connects to Python, but the interrupt button works for the regular Python kernel.

**Comment by anntzer** [comment]
FWIW the native kernel seems to support this with no problem (crosspost to #48).

**Comment by anntzer** [comment]
I have a solution but there's a separate bug in wurlitzer that affects long outputs (see above), so that'll depend on it being fixed.

**Comment by anntzer** [comment]
Vendorized wurlitzer with a fix.  Lack of windows support remains an issue; see #59.
