### ISSUE TITLE
No syntax highlighting

### ISSUE THREAD

**Issue by brunobeltran** [Calysto/matlab_kernel#50]
So I didn't realize that syntax highlighting was supposed to work. 

I can't find anything in the repo that would seem to enable it, but Github's ability to render the example notebook with syntax highlighting suggests that I'm missing out.

The same browser window on my computer correctly syntax highlights my python3 notebooks but not my matlab notebooks. Any pointers as to where I would look to try to fix this?

**Comment by blink1073** [comment]
I'm not sure what is going on here either.  I see that the `octave` codemirror mode file is loaded, but the notebook isn't using it properly.

**Comment by brunobeltran** [comment]
Found the relevant error message from Jupyter[hub]:
```
[W 2016-05-24 14:09:4.637 bbeltr1 log:47] 404 GET /lenovo/jupyterhub/user/bbeltr1/static/components/codemirror/mode/matlab/matlab.js (::ffff:***.**.**.***) 1.14ms referrer=https://work.brunobeltran.org/lenovo/jupyterhub/user/bbeltr1/notebooks/Documents/test.ipynb
```

**Comment by blink1073** [comment]
Ah, we're seeing different problems (I'm using notebook master).  Can you try upgrading `matlab_kernel` and see if it works?

**Comment by brunobeltran** [comment]
Hmm. Looks like the fix was simply to trust the notebook (File->Trust Notebook), then hard refresh the page.

Guess that makes sense, though it's unfortunate.

**Comment by anntzer** [comment]
Seems fixed now even without trusting the notebook.  Even if it's still present, it's probably an issue on the side of https://github.com/jupyter/notebook...
