### ISSUE TITLE
Do not automagically switch from system-wide to --user install of the kernelspec

### ISSUE THREAD

**Issue by anntzer** [Calysto/matlab_kernel#51]
I find the automatic switch from system-wide to --user installs in `python -mmatlab_kernel.install` rather annoying.  At least there should be a way to force a sys-wide install and error out if you don't have the permissions, e.g.
- no flag means the current behavior ("try system-wide, default to user if fails")
- `--user` means user install
- `--no-user` (or `--system`) means only system-wide.

In practice I think that the correct way to provide for kernelspec installation may be to have a command that *dumps* a kernelspec folder to a temporary place (printed on stdout) and rely on `jupyter kernelspec install` directly, e.g.
```
$ jupyter kernelspec install $(python -mmatlab_kernel.dump_kernelspec)
```
(possibly with a (yet to be implemented) flag to jupyter to clean up the folder afterwards).  This would directly offer any ability that `jupyter kernelspec install` may gain, e.g. installation to arbitrary prefixes (jupyter/jupyter_client#42, jupyter/jupyter_client#156).
Thoughts?

**Comment by dsblank** [comment]
Yes, our install code predates much of the newer developed methods, and we'd prefer that it "just work".

If we could get ours in alignment with the modern methods, that would be great.

PRs accepted :)

**Comment by anntzer** [comment]
Perhaps it may make sense to have a single implementation shared as much as possible between all metakernels, so I'll try to make a PR against metakernel instead.

**Comment by dsblank** [comment]
Yes, absolutely. Thanks for pointing that out.

**Comment by anntzer** [comment]
Closed in metakernel itself.
