### ISSUE TITLE
Autocomplete sometimes deletes struct name

### ISSUE THREAD

**Issue by brunobeltran** [Calysto/matlab_kernel#52]
So I didn't realize this when testing it, because it's not 100%, but sometimes typing
```
struct_name.fie[TAB]
```
produces
```
field_name
```
instead of the desired
```
struct_name.field_name
```
I can try to fix it this weekend, since I have a decent idea of how autocomplete works in Jupyter now. Just wanted to post this here for anyone else having the same annoying problem. 

Hopefully the solution is as simple as making the period character a word boundary in Jupyter's code for our kernel.

**Comment by luli11** [comment]
just about to post  the issue but read this, very appreciate it and look forward to the solution. Now matlab_kernel is very much a mature  web-matlab front-end

**Comment by Foucl** [comment]
Have you managed to solve this somehow, @brunobeltran? I looked at matlab_kernels [`get_completions`](https://github.com/Calysto/matlab_kernel/blob/b043342f1f464a98375145cd266883338e79cc17/matlab_kernel/kernel.py#L151) and the completions are generated by [`do_matlab_complete.m`](https://github.com/Calysto/matlab_kernel/blob/b043342f1f464a98375145cd266883338e79cc17/matlab_kernel/toolbox/do_matlab_complete.m). This all works fine, the issue should be somewhere in Metakernels [`do_complete()`](https://github.com/Calysto/metakernel/blob/master/metakernel/_metakernel.py#L469), right? Should I open an issue there? Or does anybody know how this might be tackled?

**Comment by dsblank** [comment]
The code for doing matlab completions is here: https://github.com/Calysto/matlab_kernel/blob/master/matlab_kernel/kernel.py#L151

**Comment by dsblank** [comment]
Oh, I see that you pointed to that. I guess some debugging is in order there.

**Comment by Foucl** [comment]
Would it be interesting to see if the same issues occur with Octave as matlab_kernel's backend? It seems completions are handled differently with octave. I can't get pymatbridge to work with octave on windows, but I might be able to try in a Virtualbox Ubuntu later.

**Comment by brunobeltran** [comment]
Ah, sorry. I've been rotating between labs since I started graduate school, and moved out of the MATLAB-using lab before I got a chance to look at this too deeply. Let me know if there's anyway I can help by explaining how anything works or how to setup a debug environment, since I wrote do_matlab_complete.m.

I would suggest starting by opening up a kernel manually in IPython and setting a breakpoint at the autocompletion function iff info['obj'] contains a period. It might be necessary to do some special handling of struct access in do_matlab_complete.m. If you can verify that `get_completions()` returns the correct string when called on an info object with a period in it, then I would probably blame it on MetaKernel next, but that's all just me guessing basically.

**Comment by brunobeltran** [comment]
Got guilty of not having looked into this, so I opened up the debugger and can confirm that there is a bug in do_matlab_complete.m. Basically, I suspect Metakernel expects words to break on spaces in it's autocompleter, whereas in Matlab's autocompleter, '.' acts as a word boundary. Since the struct name is required for the autocompleter to work, changing what Metakernel thinks a word boundary is won't work, so I'll have to simply have do_matlab_complete.m parse the input string for a '.' then make sure to output the correct string in that case.
