### ISSUE TITLE
Cannot install matlab_kernel

### ISSUE THREAD

**Issue by AStupidBear** [Calysto/matlab_kernel#56]
```
rluser@highchain-Z10PE-D8-WS:~$ pip install matlab_kernel
Requirement already satisfied (use --upgrade to upgrade): matlab_kernel in ./anaconda2/lib/python2.7/site-packages/matlab_kernel-0.6.10-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): metakernel>=0.10.5 in ./anaconda2/lib/python2.7/site-packages/metakernel-0.13.1-py2.7.egg (from matlab_kernel)

Requirement already satisfied (use --upgrade to upgrade): pymatbridge in ./anaconda2/lib/python2.7/site-packages/pymatbridge-0.5.2-py2.7.egg (from matlab_kernel)
Requirement already satisfied (use --upgrade to upgrade): IPython>=3.0 in ./anaconda2/lib/python2.7/site-packages (from matlab_kernel)
rluser@highchain-Z10PE-D8-WS:~$ python -m matlab_kernel install
/home/rluser/anaconda2/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
[Errno 13] Permission denied: '/usr/local/share/jupyter'
rluser@highchain-Z10PE-D8-WS:~$ sudo python -m matlab_kernel install
[sudo] password for rluser:
/usr/bin/python: No module named matlab_kernel
```

**Comment by blink1073** [comment]
Hi @AStupidBear, the first install installed `matlab_kernel` in your Anaconda environment, while the second uses your system `python`, which are different.  Assuming you want to install this in your conda environment, it should be `$ python -m matlab_kernel install`.

**Comment by AStupidBear** [comment]
I haven't seen anything different?Yao-------- Original Message --------Subject: Re: [Calysto/matlab_kernel] Cannot install matlab_kernel (#56)From: Steven Silvester To: Calysto/matlab_kernel CC: Yao Lu ,Mention Hi @AStupidBear, the first install installed matlab_kernel in your Anaconda environment, while the second uses your system python, which are different.  Assuming you want to install this in your conda environment, it should be $ python -m matlab_kernel install.

**Comment by AStupidBear** [comment]
I haven't seen anything different?Yao

**Comment by blink1073** [comment]
Ah, you are using an old version of the kernel, can you please try:

```bash
$ pip install -U matlab_kernel
$ python -m matlab_kernel install
``

**Comment by AStupidBear** [comment]
**I have updated matlab_kernel before the following codes.**


rluser@highchain-Z10PE-D8-WS:~/anaconda2/bin$
rluser@highchain-Z10PE-D8-WS:~/anaconda2/bin$ ./pip install -U matlab_kernel
```
Requirement already up-to-date: matlab_kernel in /home/rluser/anaconda2/lib/python2.7/site-packages
Requirement already up-to-date: pymatbridge in /home/rluser/anaconda2/lib/python2.7/site-packages/pymatbridge-0.5.2-py2.7.egg (from matlab_kernel)
Requirement already up-to-date: metakernel>=0.13.1 in /home/rluser/anaconda2/lib/python2.7/site-packages/metakernel-0.13.1-py2.7.egg (from matlab_kernel)
Requirement already up-to-date: IPython>=3.0 in /home/rluser/anaconda2/lib/python2.7/site-packages (from metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: pickleshare in /home/rluser/anaconda2/lib/python2.7/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: simplegeneric>0.8 in /home/rluser/anaconda2/lib/python2.7/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: backports.shutil-get-terminal-size in /home/rluser/anaconda2/lib/python2.7/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: setuptools>=18.5 in /home/rluser/anaconda2/lib/python2.7/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: traitlets in /home/rluser/anaconda2/lib/python2.7/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: pexpect; sys_platform != "win32" in /home/rluser/anaconda2/lib/python2.7/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: decorator in /home/rluser/anaconda2/lib/python2.7/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: pathlib2; python_version in "2.6 2.7 3.2 3.3" in /home/rluser/anaconda2/lib/python2.7/site-packages (from pickleshare->IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: ipython-genutils in /home/rluser/anaconda2/lib/python2.7/site-packages (from traitlets->IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: ptyprocess>=0.5 in /home/rluser/anaconda2/lib/python2.7/site-packages (from pexpect; sys_platform != "win32"->IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
Requirement already up-to-date: six in /home/rluser/anaconda2/lib/python2.7/site-packages (from pathlib2; python_version in "2.6 2.7 3.2 3.3"->pickleshare->IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
```
rluser@highchain-Z10PE-D8-WS:~/anaconda2/bin$ ./python -m matlab_kernel install
```
/home/rluser/anaconda2/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
[Errno 13] Permission denied: '/usr/local/share/jupyter'
Perhaps you want to install with `sudo` or `--user`?
```
rluser@highchain-Z10PE-D8-WS:~/anaconda2/bin$ sudo ./python -m matlab_kernel install
[sudo] password for rluser:
```
/home/rluser/anaconda2/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
jupyter: 'kernelspec' is not a Jupyter command
```

**Comment by AStupidBear** [comment]
@blink1073 Any advice?

**Comment by dsblank** [comment]
You might try:

pip install -U jupyter
pip install -U notebook

**Comment by AStupidBear** [comment]
problem solved.

**Comment by ananths1** [comment]
How did you get it? I'm having the same problem?

**Comment by GChaudhary** [comment]
@AStupidBear  I am also facing the same problem. Can you tell me what do we do next?

**Comment by blink1073** [comment]
Here are some things we can try:

```bash
python -c "import matlab_kernel; print(matlab_kernel.__path__)"
jupyter kernelspec list
```

What are the outputs of the above?

**Comment by GChaudhary** [comment]
First output -
> ['/home/gtmchaudhary/anaconda3/lib/python3.6/site-packages/matlab_kernel']


Second output -
> Available kernels:
>   python3    /home/gtmchaudhary/anaconda3/lib/python3.6/site-packages/ipykernel/resources

**Comment by blink1073** [comment]
Ohhh, there is a typo in the readme that I had copy-pasted into a comment above, the command should be: `python -m matlab_kernel.install`.

**Comment by GChaudhary** [comment]
I am still not able to fix this, please help me out.

The output is -

`username@Chaudhary-HP:~$` pip install matlab_kernel`

> Requirement already satisfied: matlab_kernel in ./anaconda3/lib/python3.6/site-packages
> Requirement already satisfied: metakernel>=0.13.1 in ./anaconda3/lib/python3.6/site-packages (from matlab_kernel)
> Requirement already satisfied: IPython>=3.0 in ./anaconda3/lib/python3.6/site-packages (from metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: pexpect>=4.2 in ./anaconda3/lib/python3.6/site-packages (from metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: simplegeneric>0.8 in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: decorator in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: pickleshare in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: traitlets>=4.2 in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: pygments in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: setuptools>=18.5 in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: wcwidth in ./anaconda3/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: six>=1.9.0 in ./anaconda3/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: packaging>=16.8 in ./anaconda3/lib/python3.6/site-packages (from setuptools>=18.5->IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: appdirs>=1.4.0 in ./anaconda3/lib/python3.6/site-packages (from setuptools>=18.5->IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> Requirement already satisfied: pyparsing in ./anaconda3/lib/python3.6/site-packages (from packaging>=16.8->setuptools>=18.5->IPython>=3.0->metakernel>=0.13.1->matlab_kernel)
> 

`username@Chaudhary-HP:~$ python -m matlab_kernel.install`

>/home/username/anaconda3/bin/python: No module named matlab_kernel.install

**Comment by dsblank** [comment]
Looks like you have multiple Python's installed. try:

```
python3.6 -m matlab_kernel.install
```

or a variation to use the same version that is connected to pip.

**Comment by blink1073** [comment]
The previous install instructions were correct, I forgot that they had been intentionally changed in #53.

**Comment by blink1073** [comment]
`python -m matlab_kernel install` should work.  Can you please try `pip install -U metakernel; python -m matlab_kernel install`?

**Comment by GChaudhary** [comment]
`gtmchaudhary@Chaudhary-HP:~$ pip install -U metakernel; `

> Requirement already up-to-date: metakernel in ./anaconda3/lib/python3.6/site-packages
> Requirement already up-to-date: IPython>=3.0 in ./anaconda3/lib/python3.6/site-packages (from metakernel)
> Requirement already up-to-date: pexpect>=4.2 in ./anaconda3/lib/python3.6/site-packages (from metakernel)
> Requirement already up-to-date: setuptools>=18.5 in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel)
> Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.4 in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel)
> Requirement already up-to-date: pickleshare in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel)
> Requirement already up-to-date: decorator in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel)
> Requirement already up-to-date: simplegeneric>0.8 in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel)
> Requirement already up-to-date: traitlets>=4.2 in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel)
> Requirement already up-to-date: pygments in ./anaconda3/lib/python3.6/site-packages (from IPython>=3.0->metakernel)
> Requirement already up-to-date: appdirs>=1.4.0 in ./anaconda3/lib/python3.6/site-packages (from setuptools>=18.5->IPython>=3.0->metakernel)
> Requirement already up-to-date: six>=1.6.0 in ./anaconda3/lib/python3.6/site-packages (from setuptools>=18.5->IPython>=3.0->metakernel)
> Requirement already up-to-date: packaging>=16.8 in ./anaconda3/lib/python3.6/site-packages (from setuptools>=18.5->IPython>=3.0->metakernel)
> Requirement already up-to-date: wcwidth in ./anaconda3/lib/python3.6/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->IPython>=3.0->metakernel)
> Requirement already up-to-date: pyparsing in ./anaconda3/lib/python3.6/site-packages (from packaging>=16.8->setuptools>=18.5->IPython>=3.0->metakernel)

`gtmchaudhary@Chaudhary-HP:~$ python -m matlab_kernel install`
> Traceback (most recent call last):
>   File "/home/gtmchaudhary/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/gtmchaudhary/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/gtmchaudhary/anaconda3/lib/python3.6/site-packages/matlab_kernel/__main__.py", line 2, in <module>
>     from .kernel import MatlabKernel
>   File "/home/gtmchaudhary/anaconda3/lib/python3.6/site-packages/matlab_kernel/kernel.py", line 11, in <module>
>     import matlab.engine
> ModuleNotFoundError: No module named 'matlab'

`gtmchaudhary@Chaudhary-HP:~$ python -m matlab_kernel.install`
>/home/gtmchaudhary/anaconda3/bin/python: No module named matlab_kernel.install

**Comment by blink1073** [comment]
Ahhh, the matlab engine itself is not installed.  See https://www.mathworks.com/help/matlab/matlab_external/install-matlab-engine-api-for-python-in-nondefault-locations.html.

**Comment by GChaudhary** [comment]
I tried installing this but since I have python3.6, I am unable to do so. Can you guide me how to downgrade to python3.5 ?

`gtmchaudhary@Chaudhary-HP:~$ cd /usr/local/MATLAB/R2016b/extern/engines/python/`

`gtmchaudhary@Chaudhary-HP:/usr/local/MATLAB/R2016b/extern/engines/python$ python setup.py install --user`
> Traceback (most recent call last):
>   File "setup.py", line 15, in <module>
>     'is %s' % _version)
> OSError: MATLAB Engine for Python supports Python version 2.7, 3.3, 3.4 and 3.5, but your version of Python is 3.6
>

**Comment by blink1073** [comment]
Hi @GChaudhary, you can either create a new conda environment as `conda create --name py36 jupyter` (see [docs](https://conda.io/docs/using/envs.html#create-an-environment)), or remove your entire Anaconda directory and start from a 3.5 install: https://repo.continuum.io/archive/index.html.

**Comment by jackbinysh** [comment]
Jupyter 4.3.0, all requirements are up to date

**Comment by dsblank** [comment]
As you are running python directly from ~/anaconda2/bin, I suspect that you need to have a proper environment. You could try:
```
export PATH=~/anaconda2/bin:$PATH
sudo python -m matlab_kernel install
```
to make sure you are finding the correct jupyter.

**Comment by jackbinysh** [comment]
Hi @dsblank , the above did not change anything - the path was set to use the version of jupyter in the Anaconda folder, which is the only version I have. 

However, running 

`~/anaconda2/bin$  ./python -m matlab_kernel install --user`

i.e taking off the sudo and and the --user flag, did seem to work, apparently the kernel is now installed. Could this have something to do with the environment variables of a user, and those used when sudo is run, differing? ( your comment above led me to think about this)

**Comment by dsblank** [comment]
Yes, using `--user` is the correct thing to do. Thanks for the note. Everything working now?

**Comment by jackbinysh** [comment]
I think so @dsblank , thanks for the help

**Comment by dsblank** [comment]
Good to hear!

**Comment by umasaxena** [comment]
Sorry to jumpstart on this thread. I am using windows7 and just installed python3.6.5 and IPython and trying to install Matlab_kernel but unable to do so either through pip or python install. I have a Matlab license. Should I configure or point the install to the Matlab license before installing Matlab_kernel ?

Any suggestions will be very helpful
