### ISSUE TITLE
Is it possible to use this with a windows install of ipython and MATLAB?

### ISSUE THREAD

**Issue by jakereimer** [Calysto/matlab_kernel#58]
I'm able to launch the kernel in one Anaconda console, and it does launch a MATLAB process. I can connect to the kernel with qtconsole and run matlab commands, but I'm not able to use the kernel with notebook.

Thanks!
Jake

**Comment by blink1073** [comment]
Hi @jakereimer, do you mean that it is not available in the `New` dropdown on the main notebook page?

**Comment by jakereimer** [comment]
Hi @blink1073, thanks for the response. Looks like I just needed to uninstall/reinstall the latest version of Anaconda to get this working. Excited to use it, thanks for this!

**Comment by blink1073** [comment]
Great, enjoy!
