### ISSUE TITLE
Detect whether the current input forms a complete code (is_complete_request)

### ISSUE THREAD

**Issue by anntzer** [Calysto/matlab_kernel#63]
It would be nice if we could detect whether the current input forms a "complete" code, and thus should respond positively to `is_complete_request` (thus skipping the need to press <enter> twice at the end of each input).
@brunobeltran Given your amazing reverse-engineering of tab completion, I thought you may be interested to loonk into this :-)

**Comment by brunobeltran** [comment]
The solution to this is probably related to the `is_continued` function exported in `bin/$ARCH/libmwm_parser.so`. That shared library also contains functions with provocative names like `are_parens_unbalanced`.

Unfortunately, there doesn't seem to be any sign that this function can be called through the Java Maltab Interface (JMI), which is how I got Matlab's built-in tab completion to work for us. There is also no sign of this function being called from anywhere obvious in the Java interface.

Maybe there's another function that can be used to get a similar result? 

There's a lot of files to dig through that might inadvertently provide an interface to Matlab's parser. The editor might be a good place to start a reverse engineering attempt. The editor class is at `com.mathworks.matlab.api.editor` and its syntax highlighting (which knows when a statement is not complete) is at `com.mathworks.matlab.api.editor`.

To dump the interfaces of these classes to text, look through the java/jar directory of your matlab installation to find a promising jar file, and use something like

```bash
for class in `jar tf $jarfile`; do
    classname=`echo $class
               | sed 's:/:.:g'
               | sed 's:.class::'
              `;
    javap -classpath $jarfile $classname >>output_file.txt;
done
```

For example, running this on `jarfile=/opt/MATLAB/R2016a/java/jar/jmi.jar` is how I found out how to call `com.mathworks.jmi.mtFindAllTabCompletions`.

Hopefully this is helpful to whoever has the time to look at this!

**Comment by anntzer** [comment]
Actually, there's a much simpler solution: we can call the `pcode` function (http://www.mathworks.com/help/matlab/ref/pcode.html) to check whether the statement compiles.  (In fact we can probably just call the undocumented builtin `_mcheck`, which is the part that checks syntactic validity (see also `checkSyntacticWarnings`), but `pcode` is documented so the interface should stay stable.)

**Comment by anntzer** [comment]
Fixed as of master.

**Comment by brunobeltran** [comment]
Excellent find @anntzer!

**Comment by anntzer** [comment]
PS: Can you give it a try?  I've been doing quite a few changes to the codebase recently so more testing is always welcome.  (In particular the kernel has become Py3.5+ only.  I can honestly not find any reason to maintain Py2 compatibility.)
