### ISSUE TITLE
Windows Matlab Dead Kernel - file path issue

### ISSUE THREAD

**Issue by loibucket** [Calysto/matlab_kernel#66]
I'm getting a dead kernel problem with running jupyter with matlab, in windows 7. I can run jupyter fine with R, OCTAVE and PYTHON, but MATLAB I get this error:

error: matlabserver: could not find library or dependents: C:\Users\username\AppD ata\Local\Continuum\Anaconda2\lib\site-packages\pymatbridge/matlab\messenger.mex

error: called from matlabserver at line 7 column 1

I don't know why there's a forward slash instead of a backslash at ...pymatbridge/matlab...
could this be causing the error?

**Comment by anntzer** [comment]
I am not supporting pymatbridge anymore.  Please follow the instructions in the README and https://www.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html or https://www.mathworks.com/help/matlab/matlab_external/install-matlab-engine-api-for-python-in-nondefault-locations.html for installation.
