### ISSUE TITLE
MATLAB kernel issue - Dead Kernel

### ISSUE THREAD

**Issue by mittal4792** [Calysto/matlab_kernel#67]
Creating a new notebook with Python works fine, but creating one with Matlab does not work.
It shows the following error.
I believe I have installed the matlab_kernel properly.

Error trace:
> [I 15:53:32.848 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
> [I 15:53:33.430 NotebookApp] [nb_conda] enabled
> [I 15:53:33.492 NotebookApp] [nb_anacondacloud] enabled
> [I 15:53:33.540 NotebookApp] \u2713 nbpresent HTML export ENABLED
> [W 15:53:33.543 NotebookApp] \u2717 nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
> [I 15:53:33.667 NotebookApp] Serving notebooks from local directory: H:\
> [I 15:53:33.669 NotebookApp] 0 active kernels
> [I 15:53:33.671 NotebookApp] The Jupyter Notebook is running at: http://localhost:8880/
> [I 15:53:33.674 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [I 15:53:47.130 NotebookApp] Kernel started: 465d2f61-6d0a-4eca-8272-3bd5efced378
> [I 15:53:53.302 NotebookApp] Kernel started: aeb0f5b8-68a5-4702-8405-b3d52d5f39d5
> C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\python.exe: No module named matlab_kernel
> [I 15:53:56.302 NotebookApp] KernelRestarter: restarting kernel (1/5)
> C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\python.exe: No module named matlab_kernel
> [I 15:53:59.319 NotebookApp] KernelRestarter: restarting kernel (2/5)
> C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\python.exe: No module named matlab_kernel
> [I 15:54:02.344 NotebookApp] KernelRestarter: restarting kernel (3/5)
> C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\python.exe: No module named matlab_kernel
> [W 15:54:03.364 NotebookApp] Timeout waiting for kernel_info reply from aeb0f5b8-68a5-4702-8405-b3d52d5f39d5
> [I 15:54:05.366 NotebookApp] KernelRestarter: restarting kernel (4/5)
> WARNING:root:kernel aeb0f5b8-68a5-4702-8405-b3d52d5f39d5 restarted
> C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\python.exe: No module named matlab_kernel
> [W 15:54:08.380 NotebookApp] KernelRestarter: restart failed
> [W 15:54:08.383 NotebookApp] Kernel aeb0f5b8-68a5-4702-8405-b3d52d5f39d5 died, removing from map.
> ERROR:root:kernel aeb0f5b8-68a5-4702-8405-b3d52d5f39d5 restarted failed!
> [W 15:54:08.451 NotebookApp] Kernel deleted before session
> [W 15:54:08.456 NotebookApp] 410 DELETE /api/sessions/48b4d31c-8951-4ba3-a618-baddaaff18e1 (::1) 6.51ms referer=http://localhost:8880/notebooks/Projects/Untitled%20Folder/Untitled1.ipynb
![1](https://cloud.githubusercontent.com/assets/18646711/19352333/7a064d18-912d-11e6-9e77-bcb79f9a2a98.JPG)

**Comment by anntzer** [comment]
> I believe I have installed the matlab_kernel properly.

Apparently you haven't:

>> C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\python.exe: No module named matlab_kernel

How did you install it?

**Comment by mittal4792** [comment]
@anntzer To install the kernel, the commands I used are:

> pip install matlab_kernel
> python -m matlab_kernel install

**Comment by anntzer** [comment]
What does `python -c "import matlab_kernel"` give?

**Comment by mittal4792** [comment]
> Traceback (most recent call last):
>   File "\<string\>", line 1, in \<module\>
> ImportError: No module named 'matlab_kernel'

**Comment by anntzer** [comment]
Hum...
`python -mpip install matlab_kernel` (instead of `pip install matlab_kernel`) then?  (Again, if it doesn't works, give the output of `python -c "import matlab_kernel"`.)

**Comment by mittal4792** [comment]
Well, after using `python -mpip install matlab_kernel` , I did not get the "No module named matlab_kernel" error on the console, but I did get the following **timeout**:

> [TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
> [TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
> [I 10:36:51.806 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
> [I 10:36:51.908 NotebookApp] [nb_anacondacloud] enabled
> [I 10:36:51.968 NotebookApp] \u2713 nbpresent HTML export ENABLED
> [W 10:36:51.969 NotebookApp] \u2717 nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
> [I 10:36:51.980 NotebookApp] [nb_conda] enabled
> [I 10:36:52.127 NotebookApp] Serving notebooks from local directory: H:\
> [I 10:36:52.128 NotebookApp] 0 active kernels
> [I 10:36:52.130 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/
> [I 10:36:52.135 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [I 10:37:02.272 NotebookApp] Creating new notebook in /Projects/Untitled Folder
> [I 10:37:03.345 NotebookApp] Kernel started: d3308f9f-34a1-4765-bfc1-e0094a2b1962
> C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
>   "You should import from nbformat instead.", ShimWarning)
> 'matlab' is not recognized as an internal or external command,
> operable program or batch file.
> [W 10:37:13.384 NotebookApp] Timeout waiting for kernel_info reply from d3308f9f-34a1-4765-bfc1-e0094a2b1962

And after using `python -c "import matlab_kernel"`, I get the following 404 error:

> [TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
> [TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
> [I 10:38:22.820 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
> [I 10:38:22.862 NotebookApp] [nb_conda] enabled
> [I 10:38:22.924 NotebookApp] \u2713 nbpresent HTML export ENABLED
> [W 10:38:22.927 NotebookApp] \u2717 nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
> [I 10:38:22.984 NotebookApp] [nb_anacondacloud] enabled
> [I 10:38:23.109 NotebookApp] Serving notebooks from local directory: H:\
> [I 10:38:23.112 NotebookApp] 0 active kernels
> [I 10:38:23.114 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/
> [I 10:38:23.122 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [I 10:38:30.799 NotebookApp] Kernel started: 1c333440-ea67-42e7-8810-6f67e1c974d2
> [W 10:38:34.539 NotebookApp] 404 GET /api/kernels/d3308f9f-34a1-4765-bfc1-e0094a2b1962/channels?session_id=B9F1836F397344238C0438204C57ADD2 (::1): Kernel does not exist: d3308f9f-34a1-4765-bfc1-e0094a2b1962
> [W 10:38:34.558 NotebookApp] 404 GET /api/kernels/d3308f9f-34a1-4765-bfc1-e0094a2b1962/channels?session_id=B9F1836F397344238C0438204C57ADD2 (::1) 23.01ms referer=None

**Comment by anntzer** [comment]
Oh, of course, that's because the latest version is not released on PyPI yet (for various reasons).

Try `python -mpip install git+https://github.com/Calysto/matlab_kernel` instead?

We'll slowly get there...

**Comment by mittal4792** [comment]
Well, I started over and used your suggested command : `python -mpip install git+https://github.com/Calysto/matlab_kernel`

Unfortunately, that did not work either.
This is what I get:

> [I 10:11:38.755 NotebookApp] **Kernel started**: 4fdccd21-584b-4da6-ab0f-39609a7eb6e5
> Traceback (most recent call last):
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\site-packages\matlab_kernel\__main__.py", line 2, in <module>
>     from .kernel import MatlabKernel
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\site-packages\matlab_kernel\kernel.py", line 11, in <module>
**>     import matlab.engine
> ImportError: No module named 'matlab'**
> [I 10:11:41.731 NotebookApp] KernelRestarter: restarting kernel (1/5)
> Traceback (most recent call last):
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\site-packages\matlab_kernel\__main__.py", line 2, in <module>
>     from .kernel import MatlabKernel
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\site-packages\matlab_kernel\kernel.py", line 11, in <module>
>     import matlab.engine
> ImportError: No module named 'matlab'

> [W 10:11:53.787 NotebookApp] KernelRestarter: restart failed
> [W 10:11:53.790 NotebookApp] Kernel 4fdccd21-584b-4da6-ab0f-39609a7eb6e5 died, removing from map.
> ERROR:root:kernel 4fdccd21-584b-4da6-ab0f-39609a7eb6e5 restarted failed!
> [W 10:11:53.823 NotebookApp] Kernel deleted before session
> [W 10:11:53.826 NotebookApp] 410 DELETE /api/sessions/284b03d4-51bb-4cfe-8c76-58755761f396 (::1) 4.03ms referer=http://localhost:8889/notebooks/Untitled%20Folder/Untitled3.ipynb

**Comment by sjain4** [comment]
Even I am getting an error while trying to use Matlab kernel
Ran the following command to install Matlab kernel:
 `python -mpip install git+https://github.com/Calysto/matlab_kernel ` 
ERROR DESCRIPTION:

> 
> [E 10:36:28.519 NotebookApp] Failed to run command:
>     ['H:\\Jupyter\\python.exe', '-m', 'matlab_kernel', '-f', 'C:\\Users\\sjain\\AppData\\Roaming\\jupyter\\runtime\\kernel-c88192b5-0aac-4d51-b435-9758e177d344.json']
>         PATH='C:\\Users\\sjain\\AppData\\Local\\Continuum\\Anaconda3\\Library\\bin;C:\\Users\\sjain\\AppData\\Local\\Continuum\\Anaconda3\\Scripts;C:\\Users\\sjain\\AppData\\Local\\Continuum\\Anaconda3\\Library\\bin;C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\MathWorks\\DevelTools\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\sjain\\AppData\\Local\\Continuum\\Anaconda3;C:\\Users\\sjain\\AppData\\Local\\Continuum\\Anaconda3\\Scripts;C:\\Users\\sjain\\AppData\\Local\\Continuum\\Anaconda3\\Library\\bin;C:\\RailsInstaller\\Git\\cmd;C:\\RailsInstaller\\Ruby2.2.0\\bin;C:\\Users\\sjain\\AppData\\Local\\atom\\bin'
>         with kwargs:
>     {'stderr': None, 'cwd': 'H:\\jupyter', 'stdin': -1, 'stdout': None}
> 
> [E 10:36:28.549 NotebookApp] Unhandled error in API request
>     Traceback (most recent call last):
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 457, in wrapper
>         result = yield gen.maybe_future(method(self, *args, **kwargs))
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
>         value = future.result()
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
>         raise_exc_info(self._exc_info)
>       File "<string>", line 3, in raise_exc_info
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
>         yielded = self.gen.throw(*exc_info)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 62, in post
>         kernel_id=kernel_id))
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
>         value = future.result()
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
>         raise_exc_info(self._exc_info)
>       File "<string>", line 3, in raise_exc_info
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
>         yielded = self.gen.throw(*exc_info)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
>         kernel_name)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
>         value = future.result()
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
>         raise_exc_info(self._exc_info)
>       File "<string>", line 3, in raise_exc_info
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 1021, in run
>         yielded = self.gen.throw(*exc_info)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
>         self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
>         value = future.result()
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
>         raise_exc_info(self._exc_info)
>       File "<string>", line 3, in raise_exc_info
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\gen.py", line 285, in wrapper
>         yielded = next(result)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
>         super(MappingKernelManager, self).start_kernel(**kwargs)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
>         km.start_kernel(**kwargs)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
>         **kw)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
>         return launch_kernel(kernel_cmd, **kw)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
>         proc = Popen(cmd, **kwargs)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 947, in __init__
>         restore_signals, start_new_session)
>       File "C:\Users\sjain\AppData\Local\Continuum\Anaconda3\lib\subprocess.py", line 1224, in _execute_child
>         startupinfo)
>     FileNotFoundError: [WinError 2] The system cannot find the file specified
> [E 10:36:28.664 NotebookApp] {
>       "Accept": "application/json, text/javascript, */*; q=0.01",
>       "Accept-Language": "en-US",
>       "X-Requested-With": "XMLHttpRequest",
>       "Host": "localhost:8889",
>       "Accept-Encoding": "gzip, deflate",
>       "Cache-Control": "no-cache",
>       "Content-Type": "application/json",
>       "Referer": "http://localhost:8889/notebooks/Untitled3.ipynb?kernel_name=matlab",
>       "Content-Length": "76",
>       "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko",
>       "Connection": "Keep-Alive"
>     }
> [E 10:36:28.694 NotebookApp] 500 POST /api/sessions (::1) 208.16ms referer=http://localhost:8889/notebooks/Untitled3.ipynb?kernel_name=matlab

**Comment by anntzer** [comment]
@mittal4792 you need to install the engine itself first... follow the instructions at http://www.mathworks.com/help/matlab/matlab_external/install-the-matlab-engine-for-python.html or possibly http://www.mathworks.com/help/matlab/matlab_external/install-matlab-engine-api-for-python-in-nondefault-locations.html

@sjain4 your issue looks similar to http://stackoverflow.com/questions/34762625/ipython-notebook-how-to-set-the-correct-path-to-kernel or https://github.com/jupyter/notebook/issues/1394.

**Comment by mittal4792** [comment]
@anntzer Followed the instructions in the link, and getting the following error:

> [I 16:10:59.995 NotebookApp] Kernel started: 0c26e24d-508c-4779-94de-4283719a7356
> Traceback (most recent call last):
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\site-packages\matlab_kernel\__main__.py", line 2, in <module>
>     from .kernel import MatlabKernel
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\site-packages\matlab_kernel\kernel.py", line 15, in <module>
>     from .wurlitzer import Wurlitzer
>   File "C:\Users\mittalp\AppData\Local\Continuum\Anaconda3\lib\site-packages\matlab_kernel\wurlitzer.py", line 15, in <module>
>     from fcntl import fcntl, F_GETFL, F_SETFL
> **_ImportError: No module named 'fcntl'_**

**Comment by anntzer** [comment]
Oh yes... Windows support.  Bah, let's try an older version.
```
pip install -I git+https://github.com/Calysto/matlab_kernel@2f6b71ebc09549153770a131496a5883587545d1
```

**Comment by mittal4792** [comment]
@anntzer Thanks! That worked. :)
But unfortunately, this doesn't work with Matlab Plots. It works only with the simple mathematical operations.
When I try [a plot example](https://www.mathworks.com/help/matlab/examples/basic-matrix-operations.html?prodcode=ML), like :
```
a = [1 2 3 4 6 4 3 4 5]
b = a + 2
plot(b)
grid on
```

It doesn't show any error on the UI, but the console shows this:

> In @(h,i)print(h,sprintf('C:\Users\mittalp\AppData\Local\Temp\tmpfxel9x80/%i',i),'-dpng','-r96')
> [I 09:35:44.090 NotebookApp] Saving file at /Untitled Folder/Untitled6.ipynb

Any suggestions?

**Comment by anntzer** [comment]
Run `%plot native` first.

**Comment by mittal4792** [comment]
@anntzer That's perfect! Thanks a lot for all the help.
Last thing, using this, it plots the figure in a separate matlab window. Is there any way that the output plot is displayed right below the code section - on the same browser tab?

**Comment by anntzer** [comment]
Yes, you need to go to the source and change
```
                            "arrayfun("
                                "@(h, i) print(h, sprintf('{}/%i', i), '-d{}', '-r{}'),"
                                "get(0, 'children'), (1:{})')".format(
                                    tmpdir,
                                    settings["format"],
                                    settings["resolution"],
                                    nfig),
```
by something like
```
"arrayfun(@(h, i) print(h, [{}, num2str(i)], '-d{}', '-r{}'), get(0, 'children'), (1:{})')"
.format(tmpdir.replace("'", "''"), settings["format"], settings["resolution"], nfig)
```
(and not call `%plot native`).

But you'll need to debug this yourself because I'm not using this feature and am not going to spend time on it :-)

**Comment by mittal4792** [comment]
@anntzer I will work on it. Thanks a lot for all the help, really appreciate it. 👍 :-)
