### ISSUE TITLE
[Errno 13] Permission denied: '/usr/local/share/jupyter'

### ISSUE THREAD

**Issue by LouisMartin** [Calysto/matlab_kernel#68]
When I run `python -m matlab_kernel install` I get this error `[Errno 13] Permission denied: '/usr/local/share/jupyter'`.
However my jupyter is located at ".local/bin/jupyter".
I am not sure on how to solve this problem, can someone help?

Thanks

**Comment by dsblank** [comment]
Quick guess:

```
python -m matlab_kernel install --user
```

**Comment by LouisMartin** [comment]
Worked perfectly thanks

**Comment by md-bd** [comment]
> Quick guess:
> 
> ```
> python -m matlab_kernel install --user
> ```

Thank you for the fix.. 
I received same error message in installing Jupyter Notebook Extensions. Solved the problem perfectly. 
thank you so much!!

**Comment by renataturing** [comment]
> Quick guess:
> 
> ```
> python -m matlab_kernel install --user
> ```

Thank you too! I had the same problem with a different installation and it fixed it! :)

**Comment by 1503-firmansyah-indra** [comment]
For installing jupyter notebook extension I run this
`pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install --user`

This works for me

**Comment by blink1073** [comment]
I updated the readme to suggest using `python -m matlab_kernel install --user`.

**Comment by ROX7** [comment]
Hello i have the same probleme running :  
`python -m pyforest install_extensions`
I have tried :
`python -m pyforest install_extensions --user` 
but it doesn't work neither, i have intead the following output :
 `Usage: python -m pyforest install_extensions
	installs notebook/lab extensions
`
 Can somone help plz ?

**Comment by ranjiGT** [comment]
> Quick guess:
> 
> ```
> python -m matlab_kernel install --user
> ```

Thank you for this!

**Comment by lyk7539511** [comment]
> Quick guess:
> 
> ```
> python -m matlab_kernel install --user
> ```

Thank U!!!

**Comment by DrZelenkaa** [comment]
> Quick guess:
> 
> ```
> python -m matlab_kernel install --user
> ```

this worked to fix:

`PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'`

After I entered:

`jupyter nbextension install --py luxwidget`

as a newb, finding a quick fix made my day. Thanks!

**Comment by arc-turus** [comment]
> Quick guess:
> jhjkhjhkjhkjh

> ```

**Comment by arc-turus** [comment]
Thanks!
BTW, I got
 [Errno 13] Permission denied: '/usr/local/share/jupyter' 
while running   
python -m ipykernel install --name=imageclassification

To overcome I ran the followings:

python -m ipykernel install --user
python -m ipykernel install --user --name=imageclassification

**Comment by adrianpabon** [comment]
> For installing jupyter notebook extension I run this `pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install --user`
> 
> This works for me

Thanks, it worked perfectly.

**Comment by naseehasalam** [comment]
> Quick guess:
> 
> ```
> python -m matlab_kernel install --user
> ```

Thank you!
