### ISSUE TITLE
Magic for functions

### ISSUE THREAD

**Issue by toddrjen** [Calysto/matlab_kernel#69]
One of the limitations of MATLAB is that you can't define functions in the REPL, they must be in a separate file.  This seems to carry over to this kernel:

    function a=test()
       disp('test')
    end

Results in:

    Error: Function definitions are not permitted in this context.

It would be nice if there was a magic for functions that would automatically save the function with the same name defined by the function and put the directory the file is in the path.

I know this can be done manually using %%file magic and then manually adding the current directory (or whatever directory you use) to the session's path, but this seems to be such a basic feature I think it warrants a dedicated macro (I know the lack of the feature is primarily MATLAB's fault).

A possible call signature would be as follows:

    %%function [-t|--directory==DIRECTORY|--parent==PARENT]

`-t` would save the file to a temporary directory (defined by pythons' `tempfile` module), `--directory` would save the file to `DIRECTORY`, and `--parent` would store the file as a subfunction of parent function `PARENT`.  These options are mutually exclusive.  I think the default directory would be a subdirectory of the current directory, perhaps `functions`.

**Comment by anntzer** [comment]
You can just call `edit /path/to/foo.m` which is directly provided by MATLAB.  The only thing this doesn't do is adding the folder to the path; I'd suggest you just create your own helper function to do that, e.g.
```
function edit_and_add(path)
    edit(path);
    [pathstr, name, ext] = fileparts(path);
    addpath(pathstr);
end
```

I don't think a magic is really warranted here.  Closing, but we can continue the discussion.

**Comment by anntzer** [comment]
Actually, thinking a bit more about it, if we restrict ourselves to 2016b -- which allows defining local functions in scripts -- one solution could be to run each input not via `eval`, but by putting the input in a script file that gets run.  "Normal" variable definitions would affect the global workspace as any script does, and function definitions could be collected (as function handles) using `localfunctions` and exported in a post-processing step.  Fortunately MATLAB does not allow defining a variable with the same name as a function in a script, so there's no priority issue.

**Comment by anntzer** [comment]
After some more thought, it's actually not so easy to embed the definitions in a wrapper function (because they would become *nested*, not *local* functions) or in a script (because they need to come at the *end* of the script).
On the other hand it may be possible to just find entries that start with `function ...` and directly not pass them to `eval` but to the relevant hander, without having to explicitly call a magic.

**Comment by anntzer** [comment]
@toddrjen Would you be interested in writing a PR?  I don't need this feature personally (`edit` is more than enough for me) so I won't write it but I can provide some hints.

Note that this repo is somewhat unmaintained these days -- we're basically stuck with the difficulties in providing live output on Windows (#59).  If you only need Linux/MacOS support, and can use 2016b, then I'd suggest starting from my rewrite (https://github.com/anntzer/matlab_kernel), which does not depend on metakernel and provides a much nicer completion system.

Basically, you need to check entries that start with `function ...`, and modify `is_complete` (for such entries) to return true only if 1) the input parses correctly and 2) the input doesn't parse correctly if `end` is appended to it -- this will make sure that the function definition is correctly already terminated by an `"end"`.

Then such inputs need to be written to whatever directory with the correct filename.  For simplicity I'd suggest hardcoding it to `/tmp/matlab-kernel` (replace `/tmp` as appropriate for other OSes, see `tempfile`) and make it changeable via an environment variable (including to a relative path).

**Comment by blink1073** [comment]
Closing as answered, feel free to reopen or submit a PR with the changes suggested above.

**Comment by SicariusNoctis** [comment]
```matlab
%%file my_func.m

function y = my_func(x)
    y = x;
end
```
