### ISSUE TITLE
how do I specify the path to `matlab`?

### ISSUE THREAD

**Issue by neuromusic** [Calysto/matlab_kernel#7]
it looks like I should be able to specify the keyword argument "excecutable"[sic?] somewhere.

``` python
class MatlabKernel(MetaKernel):

...

    def __init__(self, *args, **kwargs):
        excecutable = kwargs.pop('excecutable', 'matlab')
        super(MatlabKernel, self).__init__(*args, **kwargs)
        self._matlab = Matlab(excecutable)
        self._matlab.start()
```
where is MatlabKernel/MetaKernel getting these kwargs from? can I specify them in the kernel spec or somewhere else?

**Comment by blink1073** [comment]
Good catch, thanks!  I updated the readme with instructions on how to set the executable.

**Comment by neuromusic** [comment]
fantastic. thanks!!
