### ISSUE TITLE
perhaps slow performance

### ISSUE THREAD

**Issue by steverweber** [Calysto/matlab_kernel#70]
```
% this takes ~6 seconds on my system for jupyter to render
% however Elapsed time reports ~0.31s
close all
clear all
tic
figure(2)
h1 = mesh(peaks(150))
drawnow
toc
.................

h1 = 

  Surface with properties:

       EdgeColor: 'flat'
       LineStyle: '-'
       FaceColor: [1 1 1]
    FaceLighting: 'none'
       FaceAlpha: 1
           XData: [1x150 double]
           YData: [150x1 double]
           ZData: [150x150 double]
           CData: [150x150 double]

  Use GET to show all properties

Elapsed time is 0.312800 seconds.
```

```
% this takes ~13 seconds for jupyter to render
% however Elapsed time reports ~0.35s
close all
clear all
tic
figure(3)
h2 = mesh(peaks(250))
drawnow
toc
===================
h2 = 

  Surface with properties:

       EdgeColor: 'flat'
       LineStyle: '-'
       FaceColor: [1 1 1]
    FaceLighting: 'none'
       FaceAlpha: 1
           XData: [1x250 double]
           YData: [250x1 double]
           ZData: [250x250 double]
           CData: [250x250 double]

  Use GET to show all properties

Elapsed time is 0.345200 seconds.
```

tried using the magic plot keyword to reduce image size... but same result.
```
%plot -s 450,350
```

perhaps I don't understand something fundamental with the `tic toc` that's leading me to believe this should be faster than it is.

thanks

**Comment by anntzer** [comment]
Most of the time is spent *after* executing the code, to write the figure in a temporary png file which is then read by the notebook (you can try timing `print /tmp/foo.png -dpng` in a normal MATLAB session to confirm).  You can try `%plot native` which will display the figure in the normal MATLAB window.

Ultimately I think a proper inline plotter should find some way to embed MATLAB's JFrame into the notebook -- not that I have any idea of how to do this (if it is possible at all).

**Comment by steverweber** [comment]
confirmed issue is with print.

```
close all
clear all
tic
figure(3)
h2 = mesh(peaks(250))
drawnow
print /tmp/foo.png -dpng
toc
```

```
Elapsed time is 11.486392 seconds.
previous Elapsed time was 0.2seconds when without the print
```

This seems to be a known issue with matlab > r2013b
https://www.mathworks.com/matlabcentral/answers/157920-printing-figures-very-slow-2014b-vs-2013b
https://www.mathworks.com/matlabcentral/answers/203918-slow-plotting-performance-starting-from-matlab-r2014b
http://www.mathworks.com/matlabcentral/answers/162544-2014b-figure-printing-slow


Tested some other formats...
```
close all
clear all
tic
figure(3)
h2 = mesh(peaks(250))
drawnow
toc

tic; print /tmp/test.bmp -dbmp ; toc
tic; print /tmp/test.bmp -dbmp256 ; toc
tic; print /tmp/test.png -dpng ; toc
tic; print /tmp/test.tiff -dtiff ; toc
tic; print /tmp/test.jpg -djpeg ; toc
tic; print /tmp/test600.png -dpng -r600 ; toc
tic; print /tmp/test72.png -dpng -r72 ; toc
```

```
Elapsed time is 0.206283 seconds.
Elapsed time is 10.669354 seconds.
Elapsed time is 10.121412 seconds.
Elapsed time is 10.091048 seconds.
Elapsed time is 10.080074 seconds.
Elapsed time is 10.229765 seconds.
Elapsed time is 11.139823 seconds.
Elapsed time is 9.914176 seconds.
```

dont seem like anything is much faster for complex objects.

hope it gets resolved in r2016a or I'll might revert to r2013b

**Comment by anntzer** [comment]
I am going to close this as an upstream issue then.
