### ISSUE TITLE
Switching MATLAB versions on the fly

### ISSUE THREAD

**Issue by jat255** [Calysto/matlab_kernel#71]
Is it possible to switch between two installed versions of MATLAB "on the fly?" 

I have two versions of Matlab installed on my (Windows) machine, and the only way I can think of to switch between them would be to change my `MATLAB_EXECUTABLE` variable and reinstall the kernel. A more streamlined way to do this could be useful.

**Comment by anntzer** [comment]
I would suggest using the native kernel (I don't support pymatbridge anymore anyways) and installing the engines for separate MATLAB versions in separate conda envs or venvs.  You can then install the kernel once per engine, under different names.

**Comment by blink1073** [comment]
Closing as answered, please feel free to reopen if you disagree.
