### ISSUE TITLE
README description is inaccurate

### ISSUE THREAD

**Issue by erzk** [Calysto/matlab_kernel#75]
README.rst states that:

> This requires Jupyter Notebook with Python 3.4+

but when when I installed Matlab engine for Python I got the following error:

> MATLAB Engine for Python supports Python version 2.7, 3.3 and 3.4

I was using Python 3.5, but had to downgrade to 3.4 to install the MATLAB engine. I think that you might want to change the description to:

> This requires Jupyter Notebook with Python 3.4

**Comment by HackerMD** [comment]
Worked for me with Python 3.5.2 on Ubuntu 14.04:

```
pip install matlab_kernel
python -m matlab_kernel install
```

**Comment by erzk** [comment]
Installing `matlab_kernel` works on 3.5
The problem is that Matlab engine doesn't work on 3.5 so the description is misleading.
