### ISSUE TITLE
Pre-pending %% to each cell when downloading as matlab file

### ISSUE THREAD

**Issue by janfreyberg** [Calysto/matlab_kernel#77]
This is a suggestion, rather than a bug report. (I am also not sure if this functionality is even provided by the kernel)

I thought it could be useful to pre-pend a line that is led by `%%` when downloading matlab ipnyb notebooks. Matlab supports running code in [_sections_](https://uk.mathworks.com/help/matlab/matlab_prog/run-sections-of-programs.html), which comes close to the jupyter functionality of running code cell by cell. Sections are delineated with `%%` in matlab.

This would make passing scripts to colleagues who don't use jupyter notebooks much easier.

**Comment by dsblank** [comment]
Can you describe a bit more of what code you want to enter, and how these %% delimiters would help solve a problem?

**Comment by janfreyberg** [comment]
Yes, absolutely.

This is all about the step you take when you click `File > Download as.. > Matlab (.m)` in the jupyter notebook app.

At the moment, this produces a `.m` file that has the content of all the cells, concatenated. So for example for the first five code cells in the [sample notebook](https://github.com/Calysto/matlab_kernel/blob/master/matlab_kernel.ipynb) it produces:

```
t = linspace(0,6*pi,100);
plot(sin(t))
grid on
hold on
plot(cos(t), 'r')

%plot -s 200,150

b = 10*cos(t)+30; plot(b); grid on

a = [1,2,3]

b = a + 3;
```

In the MATLAB editor, this code could be evaluated all at once, by running the script. You can't do what you could in Jupyter, which is run each cell individually (say you only want to execute `b = 10*cos(t)+30; plot(b); grid on`)

I think it would be better if it would instead output:

```
%%
t = linspace(0,6*pi,100);
plot(sin(t))
grid on
hold on
plot(cos(t), 'r')

%% 
%plot -s 200,150

%%
b = 10*cos(t)+30; plot(b); grid on

%%
a = [1,2,3]

%%
b = a + 3;
```

This produces a neat way of then running the code in matlab, cell by cell in the same way as you can do in jupyter notebooks: place your cursor inside the cell and click _run section_ (or _Ctrl + Enter_). (Rather than running the whole script at once, you can run each cell individually).

Of course, it's possible to just manually add `%%` at the beginning of every cell in a matlab_kernel notebook (this is what I do at the moment) but if possible it would be great to have this automated.

**Comment by dsblank** [comment]
Ah, thanks for the info. Yes, this should be an issue raised on the jypyter/notbook issue tracker: https://github.com/jupyter/notebook/issues/  They had talked about allowing comments (based on the comment syntax of the language) and decided to someday let the kernel handle the download formatting. This is another option that could be handled in that manner, I think.

**Comment by janfreyberg** [comment]
OK, maybe I will do that, although presumably if they plan to outsource this to kernels in the future they may not want to work on it.

Just out of curiosity - currently this functionality is just managed via the kernel specifying `"file_extension": ".m"`?

Maybe it could be possible to make a notebook extension for this...

**Comment by blink1073** [comment]
I think the "proper" way to handle this is to add a `Matlab` exporter to [nbconvert](https://github.com/jupyter/nbconvert/tree/master/nbconvert/exporters).   https://github.com/jupyter/nbconvert/tree/master/nbconvert/exporters.

**Comment by janfreyberg** [comment]
Thanks. Sounds good - I'll take a look at it.

**Comment by janfreyberg** [comment]
I've written an exporter for nbconvert:
https://github.com/janfreyberg/matlab_nbconvert

It doesn't appear in the `Download as..` menu because that's not dynamically updated, but it does work in the command line (`jupyter nbconvert --to matlab <filename>`). It prints all markdown cells as comments in matlab and all cells start with `%%`

**Comment by blink1073** [comment]
Well done, kudos for that!  I comment on that [issue](https://github.com/jupyter/notebook/issues/2177#issuecomment-279212366).

**Comment by janfreyberg** [comment]
Thanks for the suggestion on the other issue, I fixed the mime type!

**Comment by anntzer** [comment]
https://github.com/jupyter/help/issues/40 looks relevant as well?
