### ISSUE TITLE
Error writing to output stream

### ISSUE THREAD

**Issue by neuromusic** [Calysto/matlab_kernel#8]
I'm getting an error when trying to run the example matlab kernel notebook:

![screen shot 2015-04-18 at 11 22 54 pm](https://cloud.githubusercontent.com/assets/1245615/7218410/547ee288-e622-11e4-828f-e2e908601b6b.png)

Looking more closely, it actually toggles back and forth between displaying the expected output and throwing "error writing to output stream"

That is, if I execute the cell that has `a = [1,2,3]` again, it will display the expected output. A third time and it says "Error writing to output stream". A fourth time and it is fine. Etc, etc. Same for the cell that says `disp(b)`. Nothing weird for the cells which display figs.

**Comment by neuromusic** [comment]
OK, it actually looks like the "error writing to output stream" is a Matlab error and might be a bug w/ 2014a (which is what I'm running).

http://help.mworks-project.org/discussions/problems/117-matlab-window-issue

Let me see if running a different version of Matlab fixes the problem.

**Comment by neuromusic** [comment]
Problem persists with 2011a.

**Comment by blink1073** [comment]
Hmm, I tried running the notebook again and I'm not seeing the error.  Are you able to run the following from an IPython prompt:

```python
from pymatbridge import Matlab
m = Matlab()
m.start()
m.run_code('a=[1,2,3,4]')
```

**Comment by neuromusic** [comment]
I have no problem running pymatbridge. That code returns the expected
```
{u'content': {u'code': u'a = [1,2,3,4]',
  u'datadir': u'/tmp/MatlabData/',
  u'figures': [],
  u'stdout': u'\na =\n\n     1     2     3     4\n\n'},
 u'success': u'true'}
```
A few updates:

- problem persists with R2015a
- restarting the kernel (via Kernel > Restart) **fixes the problem**
- after restarting the kernel, the PNGs are larger & higher resolution (like the ones in the example notebook versus the tiny pixelated figure in the image I posted)
- if I create a copy (via File > Make a Copy...) the new notebook works fine.

so this problem is specific to the first kernel launched.

if I restart the server *then* try to run the pymatbridge code you noted, the problem pops up w/ pymatbridge.

``` python
print mlab.run_code('a = [1,2,3,4]')
print mlab.run_code('a = [1,2,3,4]')
print mlab.run_code('a = [1,2,3,4]')
print mlab.run_code('a = [1,2,3,4]')
```
returns
```
{u'content': {u'datadir': u'/tmp/MatlabData/', u'code': u'a = [1,2,3,4]', u'figures': [], u'stdout': u'\na =\n\n     1     2     3     4\n\n'}, u'success': u'true'}
{u'content': {u'code': u'a = [1,2,3,4]', u'stdout': u'Error writing to output stream.\n\n'}, u'success': u'false'}
{u'content': {u'datadir': u'/tmp/MatlabData/', u'code': u'a = [1,2,3,4]', u'figures': [], u'stdout': u'\na =\n\n     1     2     3     4\n\n'}, u'success': u'true'}
{u'content': {u'code': u'a = [1,2,3,4]', u'stdout': u'Error writing to output stream.\n\n'}, u'success': u'false'}
```

so this seems to be a pymatbridge issue related to (same as?) arokem/python-matlab-bridge#171

**Comment by neuromusic** [comment]
I closed this issue, but it might be a good idea to have matlab_kernel better handle the `u'success': u'false'` that pymatbridge returns.
