### ISSUE TITLE
Kubuntu 14.04 installation problem

### ISSUE THREAD

**Issue by ouboub** [Calysto/matlab_kernel#90]
Hi 

i Installed pip and upgraded it 
pip install --upgrade pip
I installed jupyter
sudo pip install jupyter
but then 
sudo pip install matlab_kernel
failed with 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-QqcggU/pathlib/
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

any idea what to do?

Uwe Brauer

**Comment by blink1073** [comment]
I think the first command should be `sudo pip install --upgrade pip` to upgrade the system version.

**Comment by ouboub** [comment]
but I did this it is the first command in my list, I forgot to add sudo in the report but I did it in reality

**Comment by ouboub** [comment]
I tried it out again, now it wants the -H option for sudo

So I repeated all the steps with sudo -H and I obtain
ollecting pathlib (from matlab_kernel)
  Downloading pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 1.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HCTzk_/pathlib/setup.py", line 30, in <module>
        url='https://pathlib.readthedocs.org/',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 859, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('six>=1.6.0'))

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HCTzk_/pathlib/

so pathlib seems to be the problem no idea what to do

**Comment by blink1073** [comment]
Okay, `pathlib` is causing more trouble than it is work, I am going to remove it.

**Comment by ouboub** [comment]
ok tell me please when I can try out the installation again

**Comment by blink1073** [comment]
I just released version `0.14.0`.

**Comment by ouboub** [comment]
Ok that seems to be fine, the installation did not report any error, but where do i tell the kernel where to find the matlab binaries?

**Comment by blink1073** [comment]
It uses a library provided by Matlab, instructions are [here](https://www.mathworks.com/help/matlab/matlab-engine-for-python.html).

**Comment by blink1073** [comment]
Closing as answered, please feel free to reopen if you have any more concerns.
