### ISSUE TITLE
Issue running matlab_kernel with Anaconda on a Mac

### ISSUE THREAD

**Issue by jkitchin** [Calysto/matlab_kernel#93]
I have installed the kernel, and it works fine as a notebook. That is, I can run jupyter notebook, select Matlab as the kernel and then use it.

I am not able to run test_matlab_kernel.py though. This is the first error I get.

======================================================================
ERROR: setUpClass (jupyter_kernel_test.KernelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jkitchin/anaconda3/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 201, in get_kernel_spec
    resource_dir = d[kernel_name.lower()]
KeyError: ''"

I believe this is related to another problem I have trying to run the kernel through emacs with ob-ipython. It seems to hang, and I see this output.

Traceback (most recent call last):
  File "/Users/jkitchin/anaconda3/lib/python3.5/site-packages/matlab_kernel/kernel.py", line 67, in __init__
    self._matlab = matlab.engine.start_matlab()
  File "/Users/jkitchin/anaconda3/lib/python3.5/site-packages/matlab/engine/__init__.py", line 112, in start_matlab
    eng = future.result()
  File "/Users/jkitchin/anaconda3/lib/python3.5/site-packages/matlab/engine/futureresult.py", line 68, in result
    return self.__future.result(timeout)
  File "/Users/jkitchin/anaconda3/lib/python3.5/site-packages/matlab/engine/matlabfuture.py", line 87, in result
    handle = pythonengine.getMATLAB(self._future)
matlab.engine.EngineError: Transport stopped.

I guess the problem is on the Python side because I cannot even run this python script from the Matlab site:

```
import matlab.engine
eng = matlab.engine.start_matlab()
tf = eng.isprime(37)
print(tf)
```

But I am baffled that the notebook works and this doesn't.

Any ideas on what the problem might be?

**Comment by blink1073** [comment]
Do `which jupyter` and `which python` point to the same root path?

**Comment by jkitchin** [comment]
yes:

```
jkitchin@Johns-MacBook-Air { ~ }$ which jupyter
/Users/jkitchin/anaconda3/bin/jupyter
jkitchin@Johns-MacBook-Air { ~ }$ which python
/Users/jkitchin/anaconda3/bin/python
```

The Matlab/Python side works inconsistently for me.  If I start Matlab manually and run matlab.engine.shareEngine, then I can connect to it and run things, but the start_matlab code does not start it, and if I try to launch matlab from a python script, it crashes. 

I guess this is a problem on the matlab/python side of things, and not in the kernel.

**Comment by blink1073** [comment]
Sorry, I'm afraid I'm out of ideas.  I don't personally have a Matlab license.

**Comment by dsblank** [comment]
Closing due to lack of additional information/ideas.
