### ISSUE TITLE
How can I solve this problem?

### ISSUE THREAD

**Issue by errepeone** [Calysto/matlab_kernel#94]
When I run the following commad in order to complete the matlab_kernel installation I get an error:

`sudo python -m matlab_kernel install`

The problem is:

> Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/matlab_kernel/__main__.py", line 2, in <module>
    from .kernel import MatlabKernel
  File "/usr/local/lib/python2.7/dist-packages/matlab_kernel/kernel.py", line 24, in <module>
    import matlab.engine
  File "/usr/local/lib/python2.7/dist-packages/matlab/engine/__init__.py", line 61, in <module>
    'MathWorks Technical Support for assistance: %s' % e)
EnvironmentError: Please reinstall MATLAB Engine for Python or contact MathWorks Technical Support for assistance: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/MATLAB/R2016b/extern/engines/python/dist/matlab/engine/glnxa64/../../../../../../../bin/glnxa64/libmx.so)

So as I understand, libstdc++.so.6 is installed but in a folder inside of Matlab installation (/usr/local/MATLAB/R2016b/sys/os/glnx86/libstdc++.so.6). How can I redirect to the correct path?

**Comment by blink1073** [comment]
Does it work if you copy the library to the path it is looking for?

**Comment by errepeone** [comment]
I checked on /usr/lib/x86_64-linux-gnu/ and libstdc++.so.6 is in. Any ideas on what's the problem?

**Comment by blink1073** [comment]
Sorry, I'm not sure what else to suggest other than contacting Mathworks as the traceback suggests  (I am not affiliated with them).

**Comment by dsblank** [comment]
Closing because of lack of additional information.
