### ISSUE TITLE
Not able to see Matlab Kernel

### ISSUE THREAD

**Issue by mostlyeconmix** [Calysto/matlab_kernel#96]
Hi,

I have installed Matlab Kernel. If I try to re install I get terminal says Requirement already satisfied. But I am not able to see Matlab option. Earlier terminal was saying that \users\abhishekkumar\matlab not found while starting jupyter.

**Comment by blink1073** [comment]
Hi @mostlyeconmix, did you also run `python -m matlab_kernel install`?  If so, what is the output of `jupyter kernelspec list`?

**Comment by mostlyeconmix** [comment]
Thanks for your kind response. I resolved that issue. Now I can see Matlab
in jupyter but the kernel dies instantly I explored online and came to know
that Matlab is not  compatible with python 3.5. Is it true? I have python
3.5? Is there any fix and what would be the best way to go ahead?  Looking
forward to your kind response
.

**Comment by blink1073** [comment]
The engine and the kernel should be compatible with python 3.5.  Are you able to use the engine on its own?  

https://www.mathworks.com/help/matlab/matlab_external/get-started-with-matlab-engine-for-python.html

**Comment by mostlyeconmix** [comment]
I am not sure. Can you let me know how to check that. I'm trying on own
also.

**Comment by blink1073** [comment]
I don't have Matlab myself, the best I can say is follow the instructions on their site.

**Comment by DenisSch** [comment]
I can confirm that python3.5 is not supported. Anyone found a workaround?

**Comment by dsblank** [comment]
Made a note in the readme. Thanks!
