### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by RoyiAvital** [Calysto/matlab_kernel#98]
Could you please add "Release Notes" for each release in the Release section?

Thank You.

**Comment by RoyiAvital** [comment]
Also, How can I uninstall this Kernel?

Thank You.

**Comment by blink1073** [comment]
Hi @RoyiAvital, the command is `jupyter kernelspec uninstall matlab`.

**Comment by RoyiAvital** [comment]
What about Release Notes?

**Comment by blink1073** [comment]
I don't have the bandwidth to add release notes to all of the repos I maintain
